### ISSUE TITLE
Not working on Arch linux 

### ISSUE THREAD

**Issue by parasbhanot** [espanso/espanso#1093]
After updating the packages on Arch linux espanso is no longer working 

```
espanso log
03:42:12 [daemon(42664)] [INFO] reading configs from: "/home/parasbhanot/.config/espanso"
03:42:12 [daemon(42664)] [INFO] reading packages from: "/home/parasbhanot/.local/share/espanso/packages"
03:42:12 [daemon(42664)] [INFO] using runtime dir: "/home/parasbhanot/.local/share/espanso"
03:42:12 [daemon(42664)] [WARN] keyboard layout watcher couldn't determine active layout.
03:42:12 [daemon(42664)] [INFO] watching for changes in path: "/home/parasbhanot/.config/espanso"
03:42:12 [daemon(42664)] [INFO] espanso version: 2.1.5-beta
03:42:12 [daemon(42664)] [INFO] spawning the worker process...
03:42:12 [daemon(42664)] [INFO] binded to IPC unix socket: /home/parasbhanot/.local/share/espanso/espansodaemonv2.sock
03:42:12 [worker(42672)] [INFO] reading configs from: "/home/parasbhanot/.config/espanso"
03:42:12 [worker(42672)] [INFO] reading packages from: "/home/parasbhanot/.local/share/espanso/packages"
03:42:12 [worker(42672)] [INFO] using runtime dir: "/home/parasbhanot/.local/share/espanso"
03:42:12 [worker(42672)] [INFO] binded to IPC unix socket: /home/parasbhanot/.local/share/espanso/espansoworkerv2.sock
03:42:12 [worker(42672)] [INFO] monitoring the status of the daemon process
03:42:12 [worker(42672)] [INFO] using X11AppInfoProvider
03:42:12 [worker(42672)] [INFO] using X11Source
03:42:12 [worker(42672)] [ERROR] X11Source destruction cannot be performed, handle is null
03:42:12 [worker(42672)] [ERROR] thread 'engine thread' panicked at 'failed to initialize detector module: detection source initialization failed': espanso/src/cli/worker/engine/mod.rs:139
03:42:12 [worker(42672)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
03:42:12 [worker(42672)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
03:42:12 [daemon(42664)] [ERROR] received unexpected exit code from worker 101, exiting
```

**Comment by jwliles** [comment]
I have had the same issue since installing Garuda Linux a few days ago. This is the first time I have tried to use Espanso with Wayland though. Every other installation occurred with X11. During installation, I did get an error because I did not have `wxwidgets` installed. It was handled by installing `wxgtk2`. I am unsure if that is a factor in this issue.

```
espanso log
01:46:58 [daemon(625097)] [INFO] reading configs from: "/home/jwl_jwl/.config/espanso"
01:46:58 [daemon(625097)] [INFO] reading packages from: "/home/jwl_jwl/.config/espanso/match/packages"
01:46:58 [daemon(625097)] [INFO] using runtime dir: "/home/jwl_jwl/.cache/espanso"
01:46:58 [daemon(625097)] [WARN] keyboard layout watcher couldn't determine active layout.
01:46:58 [daemon(625097)] [INFO] watching for changes in path: "/home/jwl_jwl/.config/espanso"
01:46:58 [daemon(625097)] [INFO] espanso version: 2.1.5-beta
01:46:58 [daemon(625097)] [INFO] spawning the worker process...
01:46:58 [daemon(625097)] [INFO] binded to IPC unix socket: /home/jwl_jwl/.cache/espanso/espansodaemonv2.sock
01:46:58 [worker(625103)] [INFO] reading configs from: "/home/jwl_jwl/.config/espanso"
01:46:58 [worker(625103)] [INFO] reading packages from: "/home/jwl_jwl/.config/espanso/match/packages"
01:46:58 [worker(625103)] [INFO] using runtime dir: "/home/jwl_jwl/.cache/espanso"
01:46:58 [worker(625103)] [INFO] using WaylandAppInfoProvider
01:46:58 [worker(625103)] [INFO] binded to IPC unix socket: /home/jwl_jwl/.cache/espanso/espansoworkerv2.sock
01:46:58 [worker(625103)] [INFO] detection module will use this keyboard layout: [R=, M=, L=us, V=, O=]
01:46:58 [worker(625103)] [INFO] monitoring the status of the daemon process
01:46:58 [worker(625103)] [INFO] using EVDEVSource
01:46:58 [worker(625103)] [INFO] Querying modifier status...
01:46:58 [daemon(625097)] [ERROR] received unexpected exit code from worker 90, exiting
```

![system_info](https://user-images.githubusercontent.com/13804903/177028635-5a2b065e-a4f7-40e0-bcce-3b58b279e42f.png)
