### ISSUE TITLE
espanso start time out on Ubuntu 22.04

### ISSUE THREAD

**Issue by IOiQkhQJDy5BUlWc0w3v77OV21sSBTACka5uGOJ** [espanso/espanso#1096]
Environment: Ubuntu 22.04
Version: espanso 2.1.5-beta 

Upgraded from Ubuntu 20.04, where espanso ran without issue, to Ubuntu 22.04. Installed espanso 2.1.5-beta (wayland) from .deb file. Service register was successful. Ran "sudo setcap "cap_dac_override+p" $(which espanso)". When attempting to run "espanso start" get error: "unable to start service: timed out". Attempted "killall espanso", which returned "espanso: no process found"

**Logs**
11:46:06 [daemon(107531)] [INFO] reading configs from: "/home/user1/.config/espanso"
11:46:06 [daemon(107531)] [INFO] reading packages from: "/home/user1/.config/espanso/match/packages"
11:46:06 [daemon(107531)] [INFO] using runtime dir: "/home/user1/.cache/espanso"
11:46:06 [daemon(107531)] [INFO] watching for changes in path: "/home/user1/.config/espanso"
11:46:06 [daemon(107531)] [INFO] espanso version: 2.1.5-beta
11:46:06 [daemon(107531)] [INFO] spawning the worker process...
11:46:06 [daemon(107531)] [INFO] binded to IPC unix socket: /home/user1/.cache/espanso/espansodaemonv2.sock
11:46:06 [worker(107538)] [INFO] reading configs from: "/home/user1/.config/espanso"
11:46:06 [worker(107538)] [INFO] reading packages from: "/home/user1/.config/espanso/match/packages"
11:46:06 [worker(107538)] [INFO] using runtime dir: "/home/user1/.cache/espanso"
11:46:06 [worker(107538)] [INFO] using WaylandAppInfoProvider
11:46:06 [worker(107538)] [INFO] binded to IPC unix socket: /home/user1/.cache/espanso/espansoworkerv2.sock
11:46:06 [worker(107538)] [INFO] monitoring the status of the daemon process
11:46:06 [worker(107538)] [INFO] detection module will use this keyboard layout: [R=, M=, L=us+dvorak, V=, O=]
11:46:06 [worker(107538)] [INFO] using EVDEVSource
11:46:06 [worker(107538)] [ERROR] thread 'detect thread' panicked at 'unable to create xkb keymap: could not create xkb keymap': espanso-detect/src/evdev/mod.rs:114
11:46:06 [worker(107538)] [ERROR] thread 'engine thread' panicked at 'unable to receive from the init_rx channel: RecvError': espanso/src/cli/worker/engine/funnel/mod.rs:124
11:46:06 [worker(107538)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
11:46:06 [worker(107538)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
11:46:06 [daemon(107531)] [ERROR] received unexpected exit code from worker 101, exiting

**Comment by IOiQkhQJDy5BUlWc0w3v77OV21sSBTACka5uGOJ** [comment]
This appears related to using Dvorak and I found some partial resolution from https://github.com/federico-terzi/espanso/issues/901 by updating the config/default.yml to include

```
keyboard_layout:
  rules: "evdev"
  model: pc86
  layout: us
  variant: "dvorak-intl"
```

In Ubuntu 20.04/X11 I was able to switch back and forth between QWERTY and Dvorak without issue. Also, for some reason the apostrophes in the replacements from the triggers are being ignored. I'll keep working at it and update.

**Comment by alexlyzhov** [comment]
Adding this to `~/.config/default.yml` has helped me for colemak:

```
keyboard_layout:
  layout: us
  variant: colemak
```

**Comment by smeech** [comment]
Can this Issue be closed, or are there still problems? Wayland can be tricky.
