### ISSUE TITLE
Migration fails. Panicked

### ISSUE THREAD

**Issue by killtux** [espanso/espanso#1156]
i am running espanso on multiple computers and have the config synced over nextcloud (and created a symlink)

I tried to switch to the new v2 but when i started and choose backup and migrate something failed but said that old files where untouched. it created new config files - old where gone and i cant find them in the documents dir.

![grafik](https://user-images.githubusercontent.com/36768145/176254138-81421d4e-188c-45a8-ac2c-4a1bb60bb649.png)

so i restored the files over my nextcloud (god thanks), rewrite it to new style by hand but every time i open espanso i have to choose "compatiblity mode" or backup and migrate. in compatiblity mode everything works but the message pops up with every start like it doesnt recognize that the files are already in v2 style. migration still fails if i hit it again.

here's the log:
```
C:\Users\user>espanso log
18:12:02 [daemon(33420)] [INFO] reading configs from: "C:\\Users\\user\\AppData\\Roaming\\espanso"
18:12:02 [daemon(33420)] [INFO] reading packages from: "C:\\Users\\user\\AppData\\Roaming\\espanso\\match\\packages"
18:12:02 [daemon(33420)] [INFO] using runtime dir: "C:\\Users\\user\\AppData\\Local\\espanso"
18:12:02 [daemon(33420)] [INFO] watching for changes in path: "C:\\Users\\user\\AppData\\Roaming\\espanso"
18:12:02 [daemon(33420)] [INFO] espanso version: 2.1.5-beta
18:12:02 [daemon(33420)] [INFO] spawning the worker process...
18:12:02 [daemon(33420)] [INFO] binded to named pipe: \\.\pipe\espansodaemonv2
18:12:02 [worker(33460)] [INFO] reading configs from: "C:\\Users\\user\\AppData\\Roaming\\espanso"
18:12:02 [worker(33460)] [INFO] reading packages from: "C:\\Users\\user\\AppData\\Roaming\\espanso\\match\\packages"
18:12:02 [worker(33460)] [INFO] using runtime dir: "C:\\Users\\user\\AppData\\Local\\espanso"
18:12:02 [worker(33460)] [WARN] espanso is reading the configuration using compatibility mode, thus some features might not be available
18:12:02 [worker(33460)] [WARN] you can migrate to the new configuration format by running 'espanso migrate' in a terminal
18:12:02 [worker(33460)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
18:12:02 [worker(33460)] [INFO] using Win32AppInfoProvider
18:12:02 [worker(33460)] [INFO] monitoring the status of the daemon process
18:12:02 [worker(33460)] [INFO] using Win32Source
18:12:02 [worker(33460)] [ERROR] unable to register hotkey: ALT+SPACE
18:12:02 [worker(33460)] [INFO] using Win32Injector
18:12:02 [worker(33460)] [INFO] using Win32Clipboard
19:58:12 [migrate(30916)] [INFO] reading configs from: "C:\\Users\\user\\AppData\\Roaming\\espanso"
19:58:12 [migrate(30916)] [INFO] reading packages from: "C:\\Users\\user\\AppData\\Roaming\\espanso\\match\\packages"
19:58:12 [migrate(30916)] [INFO] using runtime dir: "C:\\Users\\user\\AppData\\Local\\espanso"
19:58:12 [migrate(30916)] [WARN] espanso is reading the configuration using compatibility mode, thus some features might not be available
19:58:12 [migrate(30916)] [WARN] you can migrate to the new configuration format by running 'espanso migrate' in a terminal
19:58:12 [migrate(30916)] [INFO] --- MIGRATION STARTED ---
19:58:12 [migrate(30916)] [INFO] backing up the configuration directory: 'C:\Users\user\AppData\Roaming\espanso'
19:58:12 [migrate(30916)] [INFO]  -> into this folder: 'C:\Users\user\Documents\espanso-migrate-backup-3'
19:58:12 [migrate(30916)] [INFO] backup completed!
19:58:12 [migrate(30916)] [INFO] converting the configuration...
19:58:12 [migrate(30916)] [ERROR] thread 'main' panicked at 'an error occurred while converting the configuration: Path "C:\Users\user\AppData\Local\Temp\espanso-migrate-out.Y7WHJrsHkQy1\out\config\default.yml" is exist': espanso\src\cli\migrate.rs:131
19:58:12 [migrate(30916)] [ERROR] ERROR: 'main' panicked at 'an error occurred while converting the configuration: Path "C:\Users\user\AppData\Local\Temp\espanso-migrate-out.Y7WHJrsHkQy1\out\config\default.yml" is exist': espanso\src\cli\migrate.rs:131
```

**Comment by federico-terzi** [comment]
@killtux I'm sorry you experienced this problem! It seems there are multiple problems going on there:
* Do you have multiple `default.yml` files? That might be causing the first error
* It seems the YAML for some of your configuration files is invalid, could you please try running them through a YAML validator and see if they are valid? http://www.yamllint.com/

Cheers :)

**Comment by codysechelski** [comment]
I'm also seeing this same error message on my mac.

I even tried replacing my default.yml with one that was created during installation. Here's my default.yml file:
```yaml
# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
```

And here's the migration portion of the log
```log
15:30:23 [migrate(81978)] [INFO] --- MIGRATION STARTED ---
15:30:23 [migrate(81978)] [INFO] backing up the configuration directory: '/Users/codysechelski/Library/Preferences/espanso'
15:30:23 [migrate(81978)] [INFO]  -> into this folder: '/Users/codysechelski/Documents/espanso-migrate-backup-7'
15:30:23 [migrate(81978)] [INFO] backup completed!
15:30:23 [migrate(81978)] [INFO] converting the configuration...
15:30:23 [migrate(81978)] [ERROR] thread 'main' panicked at 'an error occurred while converting the configuration: Path "/var/folders/ml/n4c956fx4r7b25nfsp4_6jcr0000gq/T/espanso-migrate-out.qtcfnQU4kxHr/out/config/default.yml" is exist': espanso/src/cli/migrate.rs:131
15:30:23 [migrate(81978)] [ERROR] ERROR: 'main' panicked at 'an error occurred while converting the configuration: Path "/var/folders/ml/n4c956fx4r7b25nfsp4_6jcr0000gq/T/espanso-migrate-out.qtcfnQU4kxHr/out/config/default.yml" is exist': espanso/src/cli/migrate.rs:131
```

**Comment by killtux** [comment]
> @killtux I'm sorry you experienced this problem! It seems there are multiple problems going on there:
> 
> * Do you have multiple `default.yml` files? That might be causing the first error
> * It seems the YAML for some of your configuration files is invalid, could you please try running them through a YAML validator and see if they are valid? http://www.yamllint.com/
> 
> Cheers :)

i had an defaul.yaml in root and one in config - thanks for troubleshooting. the problem with the upcoming migration window every start is now gone. yaml was ok :)
