### ISSUE TITLE
thread 'engine thread' panicked at 'failed to initialize detector module: detection source initialization failed': espanso/src/cli/worker/engine/mod.rs:139

### ISSUE THREAD

**Issue by marcogabriel** [espanso/espanso#1310]
**Describe the bug**
After changing from Xorg to Wayland on Manjaro Linux (arch based), espanso starts and panicks immediately and stops again.

**To Reproduce**
1. activate Wayland on Manjaro through /etc/gdm/custom.conf and set WaylandEnable=true
2. install espanso-wayland v2.1.6-2 from AUR
3. start espanso by `espanso start` -> `espanso started correctly!`
4. check status with `espanso status` -> `espanso is not running`

**Logs**
```
09:44:14 [daemon(1398013)] [INFO] reading configs from: "/home/mgabriel/.config/espanso"
09:44:14 [daemon(1398013)] [INFO] reading packages from: "/home/mgabriel/.config/espanso/match/packages"
09:44:14 [daemon(1398013)] [INFO] using runtime dir: "/home/mgabriel/.local/share/espanso"
09:44:14 [daemon(1398013)] [INFO] system info: Manjaro Linux v21.3.5 - kernel: 5.18.12-3-MANJARO
09:44:14 [daemon(1398013)] [INFO] watching for changes in path: "/home/mgabriel/.config/espanso"
09:44:14 [daemon(1398013)] [INFO] espanso version: 2.1.6-beta
09:44:14 [daemon(1398013)] [INFO] spawning the worker process...
09:44:14 [daemon(1398013)] [INFO] binded to IPC unix socket: /home/mgabriel/.local/share/espanso/espansodaemonv2.sock
09:44:14 [daemon(1398013)] [WARN] keyboard layout watcher couldn't determine active layout.
09:44:14 [worker(1398020)] [INFO] reading configs from: "/home/mgabriel/.config/espanso"
09:44:14 [worker(1398020)] [INFO] reading packages from: "/home/mgabriel/.config/espanso/match/packages"
09:44:14 [worker(1398020)] [INFO] using runtime dir: "/home/mgabriel/.local/share/espanso"
09:44:14 [worker(1398020)] [INFO] system info: Manjaro Linux v21.3.5 - kernel: 5.18.12-3-MANJARO
09:44:14 [worker(1398020)] [INFO] binded to IPC unix socket: /home/mgabriel/.local/share/espanso/espansoworkerv2.sock
09:44:14 [worker(1398020)] [INFO] using WaylandAppInfoProvider
09:44:14 [worker(1398020)] [INFO] monitoring the status of the daemon process
09:44:14 [worker(1398020)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
09:44:14 [worker(1398020)] [INFO] using EVDEVSource
09:44:15 [worker(1398020)] [INFO] Querying modifier status...
09:44:15 [worker(1398020)] [ERROR] thread 'engine thread' panicked at 'failed to initialize detector module: detection source initialization failed': espanso/src/cli/worker/engine/mod.rs:139
09:44:15 [worker(1398020)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
09:44:15 [worker(1398020)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
```

**Setup information**
- OS: Manjaro Linux (arch based)
- Version: espanso 2.1.6-beta

**Additional information**
- I also read through issue #901 and tried to set kb in the config, but that didn't resolve the problem. Output of setxkbmap -query:
```
rules:      evdev
model:      pc105
layout:     de,de
variant:    ,
options:    lv3:ralt_switch
```
- Output of `espanso -vv daemon`:
```
09:51:15 [daemon(1400758)] [DEBUG] (1) espanso_path: detected config directory in $HOME/.config/espanso
09:51:15 [daemon(1400758)] [DEBUG] (1) espanso_path: detected legacy runtime dir: "/home/mgabriel/.local/share/espanso"
09:51:15 [daemon(1400758)] [DEBUG] (1) espanso_path: detected default packages dir: "/home/mgabriel/.config/espanso/match/packages"
09:51:15 [daemon(1400758)] [INFO] reading configs from: "/home/mgabriel/.config/espanso"
09:51:15 [daemon(1400758)] [INFO] reading packages from: "/home/mgabriel/.config/espanso/match/packages"
09:51:15 [daemon(1400758)] [INFO] using runtime dir: "/home/mgabriel/.local/share/espanso"
09:51:15 [daemon(1400758)] [INFO] system info: Manjaro Linux v21.3.5 - kernel: 5.18.12-3-MANJARO
09:51:15 [daemon(1400758)] [ERROR] daemon is already running!
```
- Output of `espanso -vv worker`:
```
09:51:33 [worker(1400869)] [DEBUG] (1) espanso_path: detected config directory in $HOME/.config/espanso
09:51:33 [worker(1400869)] [DEBUG] (1) espanso_path: detected legacy runtime dir: "/home/mgabriel/.local/share/espanso"
09:51:33 [worker(1400869)] [DEBUG] (1) espanso_path: detected default packages dir: "/home/mgabriel/.config/espanso/match/packages"
09:51:33 [worker(1400869)] [INFO] reading configs from: "/home/mgabriel/.config/espanso"
09:51:33 [worker(1400869)] [INFO] reading packages from: "/home/mgabriel/.config/espanso/match/packages"
09:51:33 [worker(1400869)] [INFO] using runtime dir: "/home/mgabriel/.local/share/espanso"
09:51:33 [worker(1400869)] [INFO] system info: Manjaro Linux v21.3.5 - kernel: 5.18.12-3-MANJARO
09:51:33 [worker(1400869)] [DEBUG] (1) espanso_config::config::store: loaded default config at path: "/home/mgabriel/.config/espanso/config/default.yml"
09:51:33 [worker(1400869)] [DEBUG] (1) espanso_config::config::store: loaded config at path: "/home/mgabriel/.config/espanso/config/thunderbird.yml"
09:51:33 [worker(1400869)] [DEBUG] (1) espanso::patch::config_store: skipping 'alacritty_terminal_x11' patch
09:51:33 [worker(1400869)] [DEBUG] (1) espanso::patch::config_store: skipping 'emacs_x11' patch
09:51:33 [worker(1400869)] [DEBUG] (1) espanso::patch::config_store: skipping 'gedit_x11' patch
09:51:33 [worker(1400869)] [DEBUG] (1) espanso::patch::config_store: skipping 'generic_terminal_x11' patch
09:51:33 [worker(1400869)] [DEBUG] (1) espanso::patch::config_store: skipping 'kitty_terminal_x11' patch
09:51:33 [worker(1400869)] [DEBUG] (1) espanso::patch::config_store: skipping 'konsole_terminal_x11' patch
09:51:33 [worker(1400869)] [DEBUG] (1) espanso::patch::config_store: skipping 'libreoffice_writer_x11' patch
09:51:33 [worker(1400869)] [DEBUG] (1) espanso::patch::config_store: skipping 'simple_terminal_x11' patch
09:51:33 [worker(1400869)] [DEBUG] (1) espanso::patch::config_store: skipping 'simple_terminal_2_x11' patch
09:51:33 [worker(1400869)] [DEBUG] (1) espanso::patch::config_store: skipping 'terminator_terminal_x11' patch
09:51:33 [worker(1400869)] [DEBUG] (1) espanso::patch::config_store: skipping 'termite_terminal_x11' patch
09:51:33 [worker(1400869)] [DEBUG] (1) espanso::patch::config_store: skipping 'thunderbird_x11' patch
09:51:33 [worker(1400869)] [DEBUG] (1) espanso::patch::config_store: skipping 'tilix_terminal_x11' patch
09:51:33 [worker(1400869)] [DEBUG] (1) espanso::patch::config_store: skipping 'urxvt_terminal_x11' patch
09:51:33 [worker(1400869)] [DEBUG] (1) espanso::patch::config_store: skipping 'xterm_terminal_x11' patch
09:51:33 [worker(1400869)] [DEBUG] (1) espanso::patch::config_store: skipping 'yakuake_terminal_x11' patch
09:51:33 [worker(1400869)] [DEBUG] (1) espanso::patch::config_store: skipping 'virtualbox_x11' patch
09:51:33 [worker(1400869)] [DEBUG] (1) espanso::cli::worker: starting with start-reason = None
09:51:33 [worker(1400869)] [DEBUG] (1) espanso::icon: skipping extraction for '"/home/mgabriel/.local/share/espanso/iconv2.png"', as it's already present
09:51:33 [worker(1400869)] [DEBUG] (1) espanso::icon: skipping extraction for '"/home/mgabriel/.local/share/espanso/search.png"', as it's already present
09:51:33 [worker(1400869)] [DEBUG] (1) espanso::icon: skipping extraction for '"/home/mgabriel/.local/share/espanso/icon_no_background.png"', as it's already present
09:51:33 [worker(1400869)] [INFO] using WaylandAppInfoProvider
09:51:33 [worker(1400869)] [INFO] binded to IPC unix socket: /home/mgabriel/.local/share/espanso/espansoworkerv2.sock
09:51:33 [worker(1400869)] [DEBUG] (2) espanso::cli::worker::engine: using linux capabilities to grant permissions needed by EVDEV backend
09:51:33 [worker(1400869)] [DEBUG] (2) espanso::cli::worker::engine: successfully granted permissions using capabilities
09:51:33 [worker(1400869)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
09:51:33 [worker(1400869)] [INFO] using EVDEVSource
09:51:34 [worker(1400869)] [INFO] Querying modifier status...
09:51:34 [worker(1400869)] [ERROR] thread 'engine thread' panicked at 'failed to initialize detector module: detection source initialization failed': espanso/src/cli/worker/engine/mod.rs:139
09:51:34 [worker(1400869)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
09:51:34 [worker(1400869)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
```

**Comment by xircon** [comment]
I am seeing this too.

**Comment by marcogabriel** [comment]
I found the reason: I activated Wayland on Manjaro, but it was not used. I was still running x11. 
After removing `espanso-wayland` and installing `espanso-bin` afterwards, espanso is running fine again.

**Comment by xircon** [comment]
I am one hundred percent on wayland... Espanso should warn you if incompatible...
