### ISSUE TITLE
Missing dependencies documentation for manual build under wayland

### ISSUE THREAD

**Issue by Luctins** [espanso/espanso#1368]
**Describe the bug**
The required dependencies for manually building on Wayland are not described on the [site article](https://espanso.org/docs/install/linux/#install-on-wayland) and even after succeeding the build some required commands are missing.

**To Reproduce**
1. Follow the article's instructions up to the point where you run `cargo make --profile release --env NO_X11=true build-binary`,
2. The build fails missing the dbus library (package was `dbus-devel`)
3. The build fails missing a xkbcommon header (package was `libxkbcommon-devel`)
4. The build fails missing a wx binary (packages were `wxBase-devel` and `wxGTK3-devel`)
5. After finishing the build and doing the installation steps, similar to #1056 the missing package was `openssl1.1-1:1.1.1n-1.fc36.x86_64`
6. and finally after finishing the build, starting the service 'fails silently' beacause of the missing package `wl-clipboard` (for the `wl-paste` command)

**Expected behaviour**
A list of required packages for some common distribution, like ubuntu (so other distros can try to translate it to their use) or specific lists (maintained by the community).

**Logs**
After finishing build:
```log
❯ /usr/bin/espanso launcher
14:08:19 [daemon(31960)] [INFO] reading configs from: "/home/luctins/.config/espanso"
14:08:19 [daemon(31960)] [INFO] reading packages from: "/home/luctins/.config/espanso/match/packages"
14:08:19 [daemon(31960)] [INFO] using runtime dir: "/home/luctins/.local/share/espanso"
14:08:19 [daemon(31960)] [INFO] system info: Fedora Linux v36 - kernel: 5.19.6-200.fc36.x86_64
14:08:19 [daemon(31960)] [INFO] watching for changes in path: "/home/luctins/.config/espanso"
14:08:19 [daemon(31960)] [INFO] espanso version: 2.1.6-beta
14:08:19 [daemon(31960)] [INFO] spawning the worker process...
14:08:19 [daemon(31960)] [INFO] binded to IPC unix socket: /home/luctins/.local/share/espanso/espansodaemonv2.sock
14:08:19 [worker(31969)] [INFO] reading configs from: "/home/luctins/.config/espanso"
14:08:19 [worker(31969)] [INFO] reading packages from: "/home/luctins/.config/espanso/match/packages"
14:08:19 [worker(31969)] [INFO] using runtime dir: "/home/luctins/.local/share/espanso"
14:08:19 [worker(31969)] [INFO] system info: Fedora Linux v36 - kernel: 5.19.6-200.fc36.x86_64
14:08:19 [worker(31969)] [INFO] using WaylandAppInfoProvider
14:08:19 [worker(31969)] [INFO] binded to IPC unix socket: /home/luctins/.local/share/espanso/espansoworkerv2.sock
14:08:19 [worker(31969)] [INFO] monitoring the status of the daemon process
14:08:19 [worker(31969)] [INFO] detection module will use this keyboard layout: [R=, M=, L=br, V=, O=]
14:08:19 [worker(31969)] [INFO] using EVDEVSource
14:08:19 [worker(31969)] [INFO] Querying modifier status...
14:08:19 [worker(31969)] [INFO] inject module will use this keyboard layout: [R=, M=, L=br, V=, O=]
14:08:19 [worker(31969)] [INFO] using EVDEVInjector
14:08:19 [worker(31969)] [INFO] using WaylandFallbackClipboard
14:08:19 [worker(31969)] [ERROR] unable to call 'wl-paste' binary, please install the wl-clipboard package.
14:08:19 [worker(31969)] [ERROR] thread 'engine thread' panicked at 'failed to initialize clipboard module: wl-clipboard binaries are missing': espanso/src/cli/worker/engine/mod.rs:186
14:08:19 [worker(31969)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
14:08:19 [worker(31969)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
14:08:19 [daemon(31960)] [ERROR] received unexpected exit code from worker 101, exiting
thread 'main' panicked at 'failed to launch daemon: unexpected error, 'espanso daemon' returned a non-zero exit code.', espanso/src/cli/launcher/mod.rs:213:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Setup information**
- Fedora Linux 36 (Worksation Ed.) x86_64
- Version: `espanso 2.1.6-beta` manually built from b2356abe6920b60b622f20f742c768271bb89478

**Comment by Luctins** [comment]
It seems like I didn't read the instructions properly, whoops. I'm sorry.
