### ISSUE TITLE
KDE Plasma crash on start

### ISSUE THREAD

**Issue by jtagcat** [espanso/espanso#1400]
**Describe the bug**
```
okt   08 00:54:45 lakenode systemd[6240]: Started espanso.service - espanso.
░░ Subject: A start job for unit UNIT has finished successfully
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit UNIT has finished successfully.
░░ 
░░ The job identifier is 4308.
okt   08 00:54:45 lakenode espanso[130655]: 00:54:45 [daemon(130655)] [INFO] reading configs from: "/home/jc/.config/espanso"
okt   08 00:54:45 lakenode espanso[130655]: 00:54:45 [daemon(130655)] [INFO] reading packages from: "/home/jc/.config/espanso/match/packages"
okt   08 00:54:45 lakenode espanso[130655]: 00:54:45 [daemon(130655)] [INFO] using runtime dir: "/home/jc/.cache/espanso"
okt   08 00:54:45 lakenode espanso[130655]: 00:54:45 [daemon(130655)] [INFO] system info: Fedora Linux v36 - kernel: 5.19.13-200.fc36.x86_64
okt   08 00:54:45 lakenode espanso[130655]: 00:54:45 [daemon(130655)] [WARN] keyboard layout watcher couldn't determine active layout.
okt   08 00:54:45 lakenode espanso[130655]: 00:54:45 [daemon(130655)] [INFO] watching for changes in path: "/home/jc/.config/espanso"
okt   08 00:54:45 lakenode espanso[130655]: 00:54:45 [daemon(130655)] [INFO] espanso version: 2.1.7-beta
okt   08 00:54:45 lakenode espanso[130655]: 00:54:45 [daemon(130655)] [INFO] spawning the worker process...
okt   08 00:54:45 lakenode espanso[130655]: 00:54:45 [daemon(130655)] [INFO] binded to IPC unix socket: /home/jc/.cache/espanso/espansodaemonv2.sock
okt   08 00:54:45 lakenode espanso[130661]: 00:54:45 [worker(130661)] [INFO] reading configs from: "/home/jc/.config/espanso"
okt   08 00:54:45 lakenode espanso[130661]: 00:54:45 [worker(130661)] [INFO] reading packages from: "/home/jc/.config/espanso/match/packages"
okt   08 00:54:45 lakenode espanso[130661]: 00:54:45 [worker(130661)] [INFO] using runtime dir: "/home/jc/.cache/espanso"
okt   08 00:54:45 lakenode espanso[130661]: 00:54:45 [worker(130661)] [INFO] system info: Fedora Linux v36 - kernel: 5.19.13-200.fc36.x86_64
okt   08 00:54:45 lakenode espanso[130661]: 00:54:45 [worker(130661)] [INFO] binded to IPC unix socket: /home/jc/.cache/espanso/espansoworkerv2.sock
okt   08 00:54:45 lakenode espanso[130661]: 00:54:45 [worker(130661)] [INFO] using WaylandAppInfoProvider
okt   08 00:54:45 lakenode espanso[130661]: 00:54:45 [worker(130661)] [INFO] detection module will use this keyboard layout: [R=, M=, L=ee, V=nodeadkeys, O=]
okt   08 00:54:45 lakenode espanso[130661]: 00:54:45 [worker(130661)] [INFO] monitoring the status of the daemon process
okt   08 00:54:45 lakenode espanso[130661]: 00:54:45 [worker(130661)] [INFO] using EVDEVSource
okt   08 00:54:45 lakenode espanso[130661]: 00:54:45 [worker(130661)] [INFO] Querying modifier status...
okt   08 00:54:45 lakenode espanso[130661]: [wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
okt   08 00:54:46 lakenode systemd-coredump[130669]: Process 130661 (espanso) of user 1000 dumped core.
                                                     
                                                     Module linux-vdso.so.1 with build-id f1b9483b20f315f5a17762975f1663485194f598
                                                     Module UTF-32.so with build-id 845c79605163fca0b36f2864d99056a395dd19ae
                                                     Module libbrotlicommon.so.1 with build-id e2790c03a5c688b7e75e89676cdd2b5fcf247a6f
                                                     Metadata for module libbrotlicommon.so.1 owned by FDO found: {
                                                             "type" : "rpm",
                                                             "name" : "brotli",
                                                             "version" : "1.0.9-7.fc36",
                                                             "architecture" : "x86_64",
                                                             "osCpe" : "cpe:/o:fedoraproject:fedora:36"
                                                     }
                                                     
                                                     Module libicudata.so.69 with build-id 4d19cd548e77f2f9778d81cf9c27831200804bc4
                                                     Stack trace of thread 130667:
                                                     #0  0x00007f2b52e4ac4c __pthread_kill_implementation (libc.so.6 + 0x8ec4c)
                                                     #1  0x00007f2b52dfa9c6 raise (libc.so.6 + 0x3e9c6)
                                                     #2  0x00007f2b52de47f4 abort (libc.so.6 + 0x287f4)
                                                     #3  0x00005596f5e60c68 _ZN14wayland_client3imp5proxy16proxy_dispatcher17h4b3930f9d9fc3088E (espanso + 0x367c68)
                                                     #4  0x00007f2b513734d4 dispatch_event.isra.0 (libwayland-client.so.0 + 0x84d4)
                                                     #5  0x00007f2b5137373c wl_display_dispatch_queue_pending (libwayland-client.so.0 + 0x873c)
                                                     #6  0x00007f2b5137605f wl_display_roundtrip_queue (libwayland-client.so.0 + 0xb05f)
                                                     #7  0x00005596f5e00315 _ZN10scoped_tls18ScopedKey$LT$T$GT$3set17hf1a70919c351940cE (espanso + 0x307315)
                                                     #8  0x00005596f5dee4ba _ZN22smithay_client_toolkit11environment20Environment$LT$E$GT$3new17h8494e9cbc9a38e90E (espanso + 0x2f54ba)
                                                     #9  0x00005596f5e0f9d1 _ZN14espanso_detect5evdev4sync7wayland19get_modifiers_state17h96645e5bd0f8b186E (espanso + 0x3169d1)
                                                     #10 0x00005596f5dfe9d3 _ZN77_$LT$espanso_detect..evdev..EVDEVSource$u20$as$u20$espanso_detect..Source$GT$10initialize17h61fe68e4eb2e5373E (espanso + 0x3059d3)
                                                     #11 0x00005596f5ca90d4 _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17h7c34a44c78ee4b94E.llvm.13236821201237276140 (espanso + 0x1b00d4)
                                                     #12 0x00005596f5ce09ed _ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17hc02fa5ffe85461b8E (espanso + 0x1e79ed)
                                                     #13 0x00005596f63a89a3 _ZN3std3sys4unix6thread6Thread3new12thread_start17ha6436304a1170bbaE (espanso + 0x8af9a3)
                                                     #14 0x00007f2b52e48e2d start_thread (libc.so.6 + 0x8ce2d)
                                                     #15 0x00007f2b52ece1b0 __clone3 (libc.so.6 + 0x1121b0)
                                                     
                                                     Stack trace of thread 130665:
                                                     #0  0x00007f2b52ecf680 accept4 (libc.so.6 + 0x113680)
                                                     #1  0x00005596f639bec3 _ZN3std2os4unix3net8listener12UnixListener6accept17h4537ac9846939a64E (espanso + 0x8a2ec3)
                                                     #2  0x00005596f5cb49b6 _ZN88_$LT$espanso_ipc..unix..UnixIPCServer$u20$as$u20$espanso_ipc..IPCServer$LT$Event$GT$$GT$3run17hc6bb451750d9297dE (espanso + 0x1bb9b6)
                                                     #3  0x00005596f5ca8f02 _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17h78d761ae9d2e8c34E.llvm.13236821201237276140 (espanso + 0x1aff02)
                                                     #4  0x00005596f5cdfd92 _ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17h312deb3b71d84197E (espanso + 0x1e6d92)
                                                     #5  0x00005596f63a89a3 _ZN3std3sys4unix6thread6Thread3new12thread_start17ha6436304a1170bbaE (espanso + 0x8af9a3)
                                                     #6  0x00007f2b52e48e2d start_thread (libc.so.6 + 0x8ce2d)
                                                     #7  0x00007f2b52ece1b0 __clone3 (libc.so.6 + 0x1121b0)
                                                     
                                                     Stack trace of thread 130661:
                                                     #0  0x00007f2b52ec6f3d syscall (libc.so.6 + 0x10af3d)
                                                     #1  0x00005596f63a5645 _ZN3std3sys4unix5futex10futex_wait17hb9562be68bc0f4c0E (espanso + 0x8ac645)
                                                     #2  0x00005596f63927ef _ZN3std6thread12park_timeout17ha7c3debf8ba52753E (espanso + 0x8997ef)
                                                     #3  0x00005596f5dd22f5 _ZN17crossbeam_channel7context7Context4with28_$u7b$$u7b$closure$u7d$$u7d$17h37012888eb3eba8bE (espanso + 0x2d92f5)
                                                     #4  0x00005596f5dd289b _ZN17crossbeam_channel7flavors4list16Channel$LT$T$GT$4recv17h23f114360b5d8577E (espanso + 0x2d989b)
                                                     #5  0x00005596f5dd1803 _ZN17crossbeam_channel7channel17Receiver$LT$T$GT$12recv_timeout17h91a1ec43002b25efE (espanso + 0x2d8803)
                                                     #6  0x00005596f5dd164f _ZN77_$LT$espanso_ui..linux..LinuxEventLoop$u20$as$u20$espanso_ui..UIEventLoop$GT$3run17h9bf24014c79c6780E (espanso + 0x2d864f)
                                                     #7  0x00005596f5cbfdd7 _ZN7espanso3cli6worker11worker_main17h4522b38d60451b82E.llvm.13236821201237276140 (espanso + 0x1c6dd7)
                                                     #8  0x00005596f5d43f78 _ZN7espanso4main17h4687909757f4dd35E (espanso + 0x24af78)
                                                     #9  0x00005596f5ca98f3 _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17hdd2da89da947ce6fE (espanso + 0x1b08f3)
                                                     #10 0x00005596f5d614b9 _ZN3std2rt10lang_start28_$u7b$$u7b$closure$u7d$$u7d$17h7aa3e925efeeaef5E.llvm.7480628805071390271 (espanso + 0x2684b9)
                                                     #11 0x00005596f6391d1e _ZN3std2rt19lang_start_internal17h6612c8a7a6861b8bE (espanso + 0x898d1e)
                                                     #12 0x00005596f5d456c2 main (espanso + 0x24c6c2)
                                                     #13 0x00007f2b52de5550 __libc_start_call_main (libc.so.6 + 0x29550)
                                                     #14 0x00007f2b52de5609 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x29609)
                                                     #15 0x00005596f5ca5f05 _start (espanso + 0x1acf05)
                                                     
                                                     Stack trace of thread 130666:
                                                     #0  0x00007f2b52e945b5 clock_nanosleep@GLIBC_2.2.5 (libc.so.6 + 0xd85b5)
                                                     #1  0x00007f2b52e98e27 __nanosleep (libc.so.6 + 0xdce27)
                                                     #2  0x00005596f6392680 _ZN3std6thread5sleep17h60e36ff7c66b6154E (espanso + 0x899680)
                                                     #3  0x00005596f5ce7c89 _ZN7espanso3cli6worker14daemon_monitor19daemon_monitor_main17hbdd91f4b28db4b8dE (espanso + 0x1eec89)
                                                     #4  0x00005596f5ca9887 _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17hcda8463a2604a6b5E.llvm.13236821201237276140 (espanso + 0x1b0887)
                                                     #5  0x00005596f5ce0232 _ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17h77706fea9eac98c8E (espanso + 0x1e7232)
                                                     #6  0x00005596f63a89a3 _ZN3std3sys4unix6thread6Thread3new12thread_start17ha6436304a1170bbaE (espanso + 0x8af9a3)
                                                     #7  0x00007f2b52e48e2d start_thread (libc.so.6 + 0x8ce2d)
                                                     #8  0x00007f2b52ece1b0 __clone3 (libc.so.6 + 0x1121b0)
                                                     
                                                     Stack trace of thread 130664:
                                                     #0  0x00007f2b52ec6f3d syscall (libc.so.6 + 0x10af3d)
                                                     #1  0x00005596f63a5645 _ZN3std3sys4unix5futex10futex_wait17hb9562be68bc0f4c0E (espanso + 0x8ac645)
                                                     #2  0x00005596f6392739 _ZN3std6thread4park17he2abdb28e4846d4eE (espanso + 0x899739)
                                                     #3  0x00005596f5d6b4a3 _ZN17crossbeam_channel7context7Context10wait_until17hcfee614804a49d5aE (espanso + 0x2724a3)
                                                     #4  0x00005596f5d6b5f1 _ZN17crossbeam_channel7context7Context4with28_$u7b$$u7b$closure$u7d$$u7d$17h033f37e90f8f49b9E (espanso + 0x2725f1)
                                                     #5  0x00005596f5d6d0a6 _ZN17crossbeam_channel7flavors4list16Channel$LT$T$GT$4recv17h9b58897034fef2d9E (espanso + 0x2740a6)
                                                     #6  0x00005596f5d2d7ea _ZN17crossbeam_channel7channel17Receiver$LT$T$GT$4recv17h48d3dc264df72ed5E (espanso + 0x2347ea)
                                                     #7  0x00005596f5d3f8f0 _ZN7espanso3cli6worker6engine6funnel14init_and_spawn17hceae23744ae80716E (espanso + 0x2468f0)
                                                     #8  0x00005596f5cbb6e5 _ZN7espanso3cli6worker6engine20initialize_and_spawn28_$u7b$$u7b$closure$u7d$$u7d$17h7756a9603b39bb69E (espanso + 0x1c26e5)
                                                     #9  0x00005596f5ca8d84 _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17h29dda070d0067038E.llvm.13236821201237276140 (espanso + 0x1afd84)
                                                     #10 0x00005596f5ce03c9 _ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17h893eeae5c03efdbeE (espanso + 0x1e73c9)
                                                     #11 0x00005596f63a89a3 _ZN3std3sys4unix6thread6Thread3new12thread_start17ha6436304a1170bbaE (espanso + 0x8af9a3)
                                                     #12 0x00007f2b52e48e2d start_thread (libc.so.6 + 0x8ce2d)
                                                     #13 0x00007f2b52ece1b0 __clone3 (libc.so.6 + 0x1121b0)
                                                     ELF object binary architecture: AMD x86-64
░░ Subject: Process 130661 (espanso) dumped core
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ Documentation: man:core(5)
░░ 
░░ Process 130661 (espanso) crashed and dumped core.
░░ 
░░ This usually indicates a programming error in the crashing program and
░░ should be reported to its vendor as a bug.
okt   08 00:54:46 lakenode espanso[130655]: 00:54:46 [daemon(130655)] [ERROR] received unexpected exit code from worker 90, exiting
okt   08 00:54:46 lakenode espanso[130648]: thread 'main' panicked at 'failed to launch daemon: unexpected error, 'espanso daemon' returned a non-zero exit code.', espanso/src/cli/launcher/mod.rs:213:45
okt   08 00:54:46 lakenode espanso[130648]: stack backtrace:
okt   08 00:54:46 lakenode espanso[130648]:    0:     0x55d0e2bb50cd - std::backtrace_rs::backtrace::libunwind::trace::h9135f25bc195152c
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
okt   08 00:54:46 lakenode espanso[130648]:    1:     0x55d0e2bb50cd - std::backtrace_rs::backtrace::trace_unsynchronized::h015ee85be510df51
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
okt   08 00:54:46 lakenode espanso[130648]:    2:     0x55d0e2bb50cd - std::sys_common::backtrace::_print_fmt::h5fad03caa9652a2c
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:66:5
okt   08 00:54:46 lakenode espanso[130648]:    3:     0x55d0e2bb50cd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2b42ca28d244e5c7
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:45:22
okt   08 00:54:46 lakenode espanso[130648]:    4:     0x55d0e2bddc1c - core::fmt::write::h401e827d053130ed
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/fmt/mod.rs:1198:17
okt   08 00:54:46 lakenode espanso[130648]:    5:     0x55d0e2bae131 - std::io::Write::write_fmt::hffec93268f5cde32
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/io/mod.rs:1672:15
okt   08 00:54:46 lakenode espanso[130648]:    6:     0x55d0e2bb6c85 - std::sys_common::backtrace::_print::h180c4c706ee1d3fb
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:48:5
okt   08 00:54:46 lakenode espanso[130648]:    7:     0x55d0e2bb6c85 - std::sys_common::backtrace::print::hd0c35d18765761c9
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:35:9
okt   08 00:54:46 lakenode espanso[130648]:    8:     0x55d0e2bb6c85 - std::panicking::default_hook::{{closure}}::h1f023310983bc730
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:295:22
okt   08 00:54:46 lakenode espanso[130648]:    9:     0x55d0e2bb69a1 - std::panicking::default_hook::h188fec3334afd5be
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:314:9
okt   08 00:54:46 lakenode espanso[130648]:   10:     0x55d0e2bb7216 - std::panicking::rust_panic_with_hook::hf26e9d4f97b40096
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:698:17
okt   08 00:54:46 lakenode espanso[130648]:   11:     0x55d0e2bb7107 - std::panicking::begin_panic_handler::{{closure}}::hfab912107608087a
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:588:13
okt   08 00:54:46 lakenode espanso[130648]:   12:     0x55d0e2bb55c4 - std::sys_common::backtrace::__rust_end_short_backtrace::h434b685ce8d9965b
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:138:18
okt   08 00:54:46 lakenode espanso[130648]:   13:     0x55d0e2bb6e39 - rust_begin_unwind
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
okt   08 00:54:46 lakenode espanso[130648]:   14:     0x55d0e24ba8a3 - core::panicking::panic_fmt::ha6dc7f2ab2479463
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
okt   08 00:54:46 lakenode espanso[130648]:   15:     0x55d0e24ba9f3 - core::result::unwrap_failed::h42ad8e915aa0a906
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
okt   08 00:54:46 lakenode espanso[130648]:   16:     0x55d0e25651b4 - espanso::cli::launcher::launcher_main::hdc76edf0f591855a
okt   08 00:54:46 lakenode espanso[130648]:   17:     0x55d0e2558f78 - espanso::main::h4687909757f4dd35
okt   08 00:54:46 lakenode espanso[130648]:   18:     0x55d0e24be8f3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hdd2da89da947ce6f
okt   08 00:54:46 lakenode espanso[130648]:   19:     0x55d0e25764b9 - std::rt::lang_start::{{closure}}::h7aa3e925efeeaef5
okt   08 00:54:46 lakenode espanso[130648]:   20:     0x55d0e2ba6d1e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hcdfee62722e5e4b8
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:280:13
okt   08 00:54:46 lakenode espanso[130648]:   21:     0x55d0e2ba6d1e - std::panicking::try::do_call::h84ca51609826746f
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
okt   08 00:54:46 lakenode espanso[130648]:   22:     0x55d0e2ba6d1e - std::panicking::try::hd58075e533b8e0cb
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
okt   08 00:54:46 lakenode espanso[130648]:   23:     0x55d0e2ba6d1e - std::panic::catch_unwind::h1ebac24d83cb6ce2
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
okt   08 00:54:46 lakenode espanso[130648]:   24:     0x55d0e2ba6d1e - std::rt::lang_start_internal::{{closure}}::h0145388a1edd1640
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:48
okt   08 00:54:46 lakenode espanso[130648]:   25:     0x55d0e2ba6d1e - std::panicking::try::do_call::h7630182e534a0a32
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
okt   08 00:54:46 lakenode espanso[130648]:   26:     0x55d0e2ba6d1e - std::panicking::try::h05b6544f0c6331dc
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
okt   08 00:54:46 lakenode espanso[130648]:   27:     0x55d0e2ba6d1e - std::panic::catch_unwind::h77b2ba8fd3309f34
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
okt   08 00:54:46 lakenode espanso[130648]:   28:     0x55d0e2ba6d1e - std::rt::lang_start_internal::h6612c8a7a6861b8b
okt   08 00:54:46 lakenode espanso[130648]:                                at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:20
okt   08 00:54:46 lakenode espanso[130648]:   29:     0x55d0e255a6c2 - main
okt   08 00:54:46 lakenode espanso[130648]:   30:     0x7f0cd1493550 - __libc_start_call_main
okt   08 00:54:46 lakenode espanso[130648]:   31:     0x7f0cd1493609 - __libc_start_main_impl
okt   08 00:54:46 lakenode espanso[130648]:   32:     0x55d0e24baf05 - _start
okt   08 00:54:46 lakenode espanso[130648]:   33:                0x0 - <unknown>
okt   08 00:54:46 lakenode systemd[6240]: espanso.service: Main process exited, code=exited, status=101/n/a
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit UNIT has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 101.
okt   08 00:54:46 lakenode systemd[6240]: espanso.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit UNIT has entered the 'failed' state with result 'exit-code'.
okt   08 00:54:49 lakenode systemd[6240]: espanso.service: Scheduled restart job, restart counter is at 169.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ Automatic restarting of the unit UNIT has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
okt   08 00:54:49 lakenode systemd[6240]: Stopped espanso.service - espanso.
░░ Subject: A stop job for unit UNIT has finished
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A stop job for unit UNIT has finished.
░░ 
░░ The job identifier is 4323 and the job result is done.
```

**To Reproduce**
1. Install Fedora KDE, Wayland
2. Start espanso

**Comment by Vistaus** [comment]
Try the fix mentioned in https://github.com/espanso/espanso/issues/1057#issuecomment-1295064021

**Comment by jtagcat** [comment]
Resolved with latest version.
