### ISSUE TITLE
espanso service crashes at startup on debian bookworm (wayland)

### ISSUE THREAD

**Issue by khimaros** [espanso/espanso#1446]
**Describe the bug**
the service crashes immediately when started from systemd

**To Reproduce**
1. sudo apt install ./espanso-debian-wayland-amd64.deb
2. espanso service register
3. systemctl --user start espanso

**Expected behavior**
start the service

**Logs**

```
Nov 14 18:07:37 espanso[223804]: 18:07:37 [daemon(223804)] [INFO] system info: Debian GNU/Linux v - kernel: 6.0.0-3-amd64
Nov 14 18:07:37 espanso[223804]: 18:07:37 [daemon(223804)] [INFO] espanso version: 2.1.8
Nov 14 18:07:37 espanso[223804]: 18:07:37 [daemon(223804)] [INFO] spawning the worker process...
Nov 14 18:07:37 espanso[223804]: 18:07:37 [daemon(223804)] [WARN] keyboard layout watcher couldn't determine active layout.
Nov 14 18:07:37 espanso[223811]: 18:07:37 [worker(223811)] [INFO] system info: Debian GNU/Linux v - kernel: 6.0.0-3-amd64
Nov 14 18:07:37 espanso[223811]: 18:07:37 [worker(223811)] [INFO] binded to IPC unix socket: /home/pawalls/.cache/espanso/espansoworkerv2.sock
Nov 14 18:07:37 espanso[223811]: 18:07:37 [worker(223811)] [INFO] using WaylandAppInfoProvider
Nov 14 18:07:37 espanso[223811]: 18:07:37 [worker(223811)] [WARN] EVDEV backend is being used, but without enabling linux capabilities.
Nov 14 18:07:37 espanso[223811]: 18:07:37 [worker(223811)] [INFO] monitoring the status of the daemon process
Nov 14 18:07:37 espanso[223811]: 18:07:37 [worker(223811)] [WARN]   Although you CAN run espanso EVDEV backend as root, it's not recommended due
Nov 14 18:07:37 espanso[223811]: 18:07:37 [worker(223811)] [WARN]   to security reasons. Espanso supports linux capabilities to limit the attack surface
Nov 14 18:07:37 espanso[223811]: 18:07:37 [worker(223811)] [WARN]   area by only leveraging on the CAP_DAC_OVERRIDE capability (needed to work with
Nov 14 18:07:37 espanso[223811]: 18:07:37 [worker(223811)] [WARN]   /dev/input/* devices to detect and inject text) and disabling it as soon as the
Nov 14 18:07:37 espanso[223811]: 18:07:37 [worker(223811)] [WARN]   initial setup is completed.
Nov 14 18:07:37 espanso[223811]: 18:07:37 [worker(223811)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
Nov 14 18:07:37 espanso[223811]: 18:07:37 [worker(223811)] [INFO] using EVDEVSource
Nov 14 18:07:37 espanso[223811]: 18:07:37 [worker(223811)] [INFO] Querying modifier status...
Nov 14 18:07:37 espanso[223811]: 18:07:37 [worker(223811)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
Nov 14 18:07:37 espanso[223811]: 18:07:37 [worker(223811)] [INFO] using EVDEVInjector
Nov 14 18:07:37 espanso[223811]: 18:07:37 [worker(223811)] [ERROR] Error: could not open uinput device
Nov 14 18:07:37 espanso[223811]: 18:07:37 [worker(223811)] [ERROR] This might be due to a recent kernel update, please restart your PC so that the uinput module can be loaded correctly.
Nov 14 18:07:37 espanso[223811]: 18:07:37 [worker(223811)] [ERROR] thread 'engine thread' panicked at 'failed to initialize injector module: could not open uinput device': espanso/src/cli/worker/engine/mod.rs:184
Nov 14 18:07:37 espanso[223811]: 18:07:37 [worker(223811)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
Nov 14 18:07:37 espanso[223811]: 18:07:37 [worker(223811)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
Nov 14 18:07:37 espanso[223804]: 18:07:37 [daemon(223804)] [ERROR] received unexpected exit code from worker 101, exiting
Nov 14 18:07:37 espanso[223796]: thread 'main' panicked at 'failed to launch daemon: unexpected error, 'espanso daemon' returned a non-zero exit code.', espanso/src/cli/launcher/mod.rs:213:45
Nov 14 18:07:37 espanso[223796]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 14 18:07:37 systemd[2637]: espanso.service: Main process exited, code=exited, status=101/n/a
Nov 14 18:07:37 systemd[2637]: espanso.service: Failed with result 'exit-code'.
```

**Setup information**
- OS: debian bookworm
- Version: espanso 2.1.8

**Comment by khimaros** [comment]
the root cause seems to be that `/dev/uinput` was not readable by my user.

i was able to work around this by creating a udev rule:

```shell
$ sudo adduser $USER input

$ cat <<EOF | sudo tee /etc/udev/rules.d/80-uinput.rules 
KERNEL=="uinput", GROUP="input", OPTIONS+="static_node=uinput", MODE=0660
EOF

$ sudo udevadm trigger
```

in some cases, a reboot may be required (or making sure the systemd user slice is stopped).

**Comment by smeech** [comment]
I suspect it may be difficult to say, but this is an old Issue and I wonder if it's been resolved by the current release?

**Comment by ditschi** [comment]
I just downloaded and installed espanso in my ubuntu 22.04. I face the same issue

**Comment by khimaros** [comment]
i'm now running debian trixie.

i tried to test this out but currently bumping against https://github.com/espanso/espanso/issues/1793
