### ISSUE TITLE
Espanso starts with tiny window which crashes Wayland

### ISSUE THREAD

**Issue by opennomad** [espanso/espanso#1619]
**Describe the bug**
Running Espanso on EndeavourOS using Wayland starts a small window, which vanishes as soon as another window is opened and notifies that "Espanso is running". The issue arises when clicking on that window, which crashes Wayland.

This only appears to happen on first login after boot.

**To Reproduce**
1. set Espanso to autostart
2. reboot and login
3. click on / attempt to resize / interact with the window

**Expected behavior**
No window shows

**Screenshots**
![image](https://github.com/espanso/espanso/assets/4350520/8d11587f-c3b4-4336-9514-4fccf730d485)
**Logs**
If possible, run `espanso log` in a terminal after the bug has occurred, then post the output here so that we can better diagnose the problem

**Setup information**
- OS: EndeavourOS
- Version: 2.1.8

**Comment by eldelacajita** [comment]
Same issue here.

 I'm using:

- GNOME 44.3 with Wayland  
- EndeavourOS 2022.04.08   
- espanso 2.1.8

I hadn't noticed Wayland crashing because I usually close the tiny window from the GNOME overview without issues, but I've tried it now and clicking on the window does crash the system and restarts the session.

Edit: It also happens on Fedora, using GNOME 44.2, Wayland and espanso 2.1.8
Edit2 in january 2024: In espanso 2.2.1, the window can't even be closed.

**Comment by opennomad** [comment]
The new release of 2.2.1 has changed the behavior. The little window shows up, but no longer crashes Wayland when you click on it. No the window is entirely unresponsive/non-interactive and adds some strange text artifact that appears to extend along the left side of the screen.

This new window also does not vanish, but hangs around.

![image](https://github.com/espanso/espanso/assets/4350520/edd13023-c18f-4627-b6f0-102aed24c67f)

**Comment by opennomad** [comment]
Interestingly, while the window can't seem to be resized, it seems possible focus it and hit enter a couple of times. After a couple of key mashes, the window closes and espanso restarts. Here is what that looks like in logs:

```
Jan 04 07:43:45 siena espanso.desktop[22362]: 07:43:45 [daemon(22362)] [INFO] reading configs from: "/home/matthias/.config/espanso"
Jan 04 07:43:45 siena espanso.desktop[22362]: 07:43:45 [daemon(22362)] [INFO] reading packages from: "/home/matthias/.config/espanso/match/packages"
Jan 04 07:43:45 siena espanso.desktop[22362]: 07:43:45 [daemon(22362)] [INFO] using runtime dir: "/home/matthias/.cache/espanso"
Jan 04 07:43:45 siena espanso.desktop[22362]: 07:43:45 [daemon(22362)] [INFO] system info: EndeavourOS vrolling - kernel: 6.6.9-arch1-1
Jan 04 07:43:45 siena espanso.desktop[22362]: 07:43:45 [daemon(22362)] [INFO] watching for changes in path: "/home/matthias/.config/espanso"
Jan 04 07:43:45 siena espanso.desktop[22362]: 07:43:45 [daemon(22362)] [INFO] espanso version: 2.2.1
Jan 04 07:43:45 siena espanso.desktop[22362]: 07:43:45 [daemon(22362)] [INFO] spawning the worker process...
Jan 04 07:43:45 siena espanso.desktop[22362]: 07:43:45 [daemon(22362)] [INFO] binded to IPC unix socket: /home/matthias/.cache/espanso/espansodaemonv2.sock
Jan 04 07:43:45 siena espanso.desktop[22362]: 07:43:45 [daemon(22362)] [WARN] keyboard layout watcher couldn't determine active layout.
Jan 04 07:43:45 siena espanso.desktop[22369]: 07:43:45 [worker(22369)] [INFO] reading configs from: "/home/matthias/.config/espanso"
Jan 04 07:43:45 siena espanso.desktop[22369]: 07:43:45 [worker(22369)] [INFO] reading packages from: "/home/matthias/.config/espanso/match/packages"
Jan 04 07:43:45 siena espanso.desktop[22369]: 07:43:45 [worker(22369)] [INFO] using runtime dir: "/home/matthias/.cache/espanso"
Jan 04 07:43:45 siena espanso.desktop[22369]: 07:43:45 [worker(22369)] [INFO] system info: EndeavourOS vrolling - kernel: 6.6.9-arch1-1
Jan 04 07:43:45 siena espanso.desktop[22369]: 07:43:45 [worker(22369)] [INFO] binded to IPC unix socket: /home/matthias/.cache/espanso/espansoworkerv2.sock
Jan 04 07:43:45 siena espanso.desktop[22369]: 07:43:45 [worker(22369)] [INFO] using WaylandAppInfoProvider
Jan 04 07:43:45 siena espanso.desktop[22369]: 07:43:45 [worker(22369)] [INFO] detection module will use this keyboard layout: [R=, M=, L=us, V=, O=]
Jan 04 07:43:45 siena espanso.desktop[22369]: 07:43:45 [worker(22369)] [INFO] monitoring the status of the daemon process
Jan 04 07:43:45 siena espanso.desktop[22369]: 07:43:45 [worker(22369)] [INFO] using EVDEVSource
Jan 04 07:43:46 siena espanso.desktop[22369]: 07:43:46 [worker(22369)] [INFO] Querying modifier status...
Jan 04 07:43:46 siena espanso.desktop[22369]: 07:43:46 [worker(22369)] [INFO] inject module will use this keyboard layout: [R=, M=, L=us, V=, O=]
Jan 04 07:43:46 siena espanso.desktop[22369]: 07:43:46 [worker(22369)] [INFO] using EVDEVInjector
Jan 04 07:43:46 siena espanso.desktop[22369]: 07:43:46 [worker(22369)] [INFO] using WaylandFallbackClipboard
Jan 04 07:43:58 siena espanso.desktop[22362]: 07:43:58 [daemon(22362)] [ERROR] received unexpected exit code from worker 90, exiting
Jan 04 07:43:58 siena espanso.desktop[22352]: thread 'main' panicked at espanso/src/cli/launcher/mod.rs:213:45:
Jan 04 07:43:58 siena espanso.desktop[22352]: failed to launch daemon: unexpected error, 'espanso daemon' returned a non-zero exit code.
Jan 04 07:43:58 siena espanso.desktop[22352]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by opennomad** [comment]
I tried getting the backtrace, but setting it at the shell (`export RUST_BACKTRACE=1`) didn't produce any other output. Also, it seems that hitting `Enter` 4 times in the window will make it crash consistently.

text expansion works otherwise

**Comment by ashish-kus** [comment]
Same issue, using:
[
![Screenshot from 2024-01-08 04-15-25](https://github.com/espanso/espanso/assets/78788195/96cdcb34-1f04-4837-a743-37477f241da8)
](url)
OS: EndeavourOS 
DE: GNOME 45.2 (wayland)
espanso 2.2.1


Wayland crashes occasionally when moving a window to a different workspace, requiring a restart to resolve. The issue persists until the cursor interacts with the affected window. Additionally, the task switcher marks it as an unknown app, though some systems recognize it as the "Espanso Sync Tool."

Note: Espanso 2.1.8 had no issue.

**Comment by opennomad** [comment]
I've downgraded to 2.1.8 by rebuilding that version from the AUR package and that is working as expected.

**Comment by sanmue** [comment]
Hi, same here bit no crash:
OS: EndeavourOS Linux x86_64
Kernel: 6.7.3-arch1-1
DE: GNOME 45.3
WM: Mutter
Wayland
AMD GPU
espanso version: 2.2.1, AUR

```
journalctl -b | grep -i 'espanso.*]: '

Feb 03 09:43:37 PC-01 espanso[3000]: 09:43:37 [daemon(3000)] [INFO] reading configs from: "/home/userid/.config/espanso"
Feb 03 09:43:37 PC-01 espanso[3000]: 09:43:37 [daemon(3000)] [INFO] reading packages from: "/home/userid/.config/espanso/match/packages"
Feb 03 09:43:37 PC-01 espanso[3000]: 09:43:37 [daemon(3000)] [INFO] using runtime dir: "/home/userid/.cache/espanso"
Feb 03 09:43:37 PC-01 espanso[3000]: 09:43:37 [daemon(3000)] [INFO] system info: EndeavourOS vrolling - kernel: 6.7.3-arch1-1
Feb 03 09:43:37 PC-01 espanso[3000]: 09:43:37 [daemon(3000)] [INFO] watching for changes in path: "/home/userid/.config/espanso"
Feb 03 09:43:37 PC-01 espanso[3000]: 09:43:37 [daemon(3000)] [INFO] espanso version: 2.2.1
Feb 03 09:43:37 PC-01 espanso[3000]: 09:43:37 [daemon(3000)] [INFO] spawning the worker process...
Feb 03 09:43:37 PC-01 espanso[3000]: 09:43:37 [daemon(3000)] [INFO] binded to IPC unix socket: /home/userid/.cache/espanso/espansodaemonv2.sock
Feb 03 09:43:37 PC-01 espanso[3000]: 09:43:37 [daemon(3000)] [WARN] keyboard layout watcher couldn't determine active layout.
Feb 03 09:43:37 PC-01 espanso[3008]: 09:43:37 [worker(3008)] [INFO] reading configs from: "/home/userid/.config/espanso"
Feb 03 09:43:37 PC-01 espanso[3008]: 09:43:37 [worker(3008)] [INFO] reading packages from: "/home/userid/.config/espanso/match/packages"
Feb 03 09:43:37 PC-01 espanso[3008]: 09:43:37 [worker(3008)] [INFO] using runtime dir: "/home/userid/.cache/espanso"
Feb 03 09:43:37 PC-01 espanso[3008]: 09:43:37 [worker(3008)] [INFO] system info: EndeavourOS vrolling - kernel: 6.7.3-arch1-1
Feb 03 09:43:37 PC-01 espanso[3008]: 09:43:37 [worker(3008)] [INFO] binded to IPC unix socket: /home/userid/.cache/espanso/espansoworkerv2.sock
Feb 03 09:43:37 PC-01 espanso[3008]: 09:43:37 [worker(3008)] [INFO] using WaylandAppInfoProvider
Feb 03 09:43:37 PC-01 espanso[3008]: 09:43:37 [worker(3008)] [INFO] detection module will use this keyboard layout: [R=, M=, L=de, V=, O=]
Feb 03 09:43:37 PC-01 espanso[3008]: 09:43:37 [worker(3008)] [INFO] monitoring the status of the daemon process
Feb 03 09:43:37 PC-01 espanso[3008]: 09:43:37 [worker(3008)] [INFO] using EVDEVSource
Feb 03 09:43:38 PC-01 espanso[3008]: 09:43:38 [worker(3008)] [INFO] Querying modifier status...
Feb 03 09:43:38 PC-01 espanso[3008]: 09:43:38 [worker(3008)] [ERROR] thread 'engine thread' panicked at 'failed to initialize detector module: detection source initialization failed': espanso/src/cli/worker/engine/mod.rs:140
Feb 03 09:43:38 PC-01 espanso[3008]: 09:43:38 [worker(3008)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
Feb 03 09:43:38 PC-01 espanso[3008]: 09:43:38 [worker(3008)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
Feb 03 09:43:39 PC-01 espanso[3000]: 09:43:39 [daemon(3000)] [ERROR] received unexpected exit code from worker 101, exiting
Feb 03 09:43:39 PC-01 espanso[2957]: thread 'main' panicked at espanso/src/cli/launcher/mod.rs:213:45:
Feb 03 09:43:39 PC-01 espanso[2957]: failed to launch daemon: unexpected error, 'espanso daemon' returned a non-zero exit code.
Feb 03 09:43:39 PC-01 espanso[2957]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Feb 03 09:43:42 PC-01 espanso[4632]: 09:43:42 [daemon(4632)] [INFO] reading configs from: "/home/userid/.config/espanso"
Feb 03 09:43:42 PC-01 espanso[4632]: 09:43:42 [daemon(4632)] [INFO] reading packages from: "/home/userid/.config/espanso/match/packages"
Feb 03 09:43:42 PC-01 espanso[4632]: 09:43:42 [daemon(4632)] [INFO] using runtime dir: "/home/userid/.cache/espanso"
Feb 03 09:43:42 PC-01 espanso[4632]: 09:43:42 [daemon(4632)] [INFO] system info: EndeavourOS vrolling - kernel: 6.7.3-arch1-1
Feb 03 09:43:42 PC-01 espanso[4632]: 09:43:42 [daemon(4632)] [INFO] watching for changes in path: "/home/userid/.config/espanso"
Feb 03 09:43:42 PC-01 espanso[4632]: 09:43:42 [daemon(4632)] [INFO] espanso version: 2.2.1
Feb 03 09:43:42 PC-01 espanso[4632]: 09:43:42 [daemon(4632)] [INFO] spawning the worker process...
Feb 03 09:43:42 PC-01 espanso[4632]: 09:43:42 [daemon(4632)] [INFO] binded to IPC unix socket: /home/userid/.cache/espanso/espansodaemonv2.sock
Feb 03 09:43:42 PC-01 espanso[4632]: 09:43:42 [daemon(4632)] [WARN] keyboard layout watcher couldn't determine active layout.
Feb 03 09:43:42 PC-01 espanso[4640]: 09:43:42 [worker(4640)] [INFO] reading configs from: "/home/userid/.config/espanso"
Feb 03 09:43:42 PC-01 espanso[4640]: 09:43:42 [worker(4640)] [INFO] reading packages from: "/home/userid/.config/espanso/match/packages"
Feb 03 09:43:42 PC-01 espanso[4640]: 09:43:42 [worker(4640)] [INFO] using runtime dir: "/home/userid/.cache/espanso"
Feb 03 09:43:42 PC-01 espanso[4640]: 09:43:42 [worker(4640)] [INFO] system info: EndeavourOS vrolling - kernel: 6.7.3-arch1-1
Feb 03 09:43:42 PC-01 espanso[4640]: 09:43:42 [worker(4640)] [INFO] using WaylandAppInfoProvider
Feb 03 09:43:42 PC-01 espanso[4640]: 09:43:42 [worker(4640)] [INFO] binded to IPC unix socket: /home/userid/.cache/espanso/espansoworkerv2.sock
Feb 03 09:43:42 PC-01 espanso[4640]: 09:43:42 [worker(4640)] [INFO] detection module will use this keyboard layout: [R=, M=, L=de, V=, O=]
Feb 03 09:43:42 PC-01 espanso[4640]: 09:43:42 [worker(4640)] [INFO] monitoring the status of the daemon process
Feb 03 09:43:42 PC-01 espanso[4640]: 09:43:42 [worker(4640)] [INFO] using EVDEVSource
Feb 03 09:43:43 PC-01 espanso[4640]: 09:43:43 [worker(4640)] [INFO] Querying modifier status...
Feb 03 09:43:48 PC-01 espanso[4640]: 09:43:48 [worker(4640)] [INFO] inject module will use this keyboard layout: [R=, M=, L=de, V=, O=]
Feb 03 09:43:48 PC-01 espanso[4640]: 09:43:48 [worker(4640)] [INFO] using EVDEVInjector
Feb 03 09:43:48 PC-01 espanso[4640]: 09:43:48 [worker(4640)] [INFO] using WaylandFallbackClipboard
```

![Screenshot from 2024-02-03 09-06-51](https://github.com/espanso/espanso/assets/38841410/14fc1a0d-244a-42ad-a65e-17189fc49300)

![Screenshot from 2024-02-03 09-07-14](https://github.com/espanso/espanso/assets/38841410/6f7644dc-cd99-42e5-9f32-164042bde6eb)

![Screenshot from 2024-02-03 09-58-28](https://github.com/espanso/espanso/assets/38841410/43c2ec9a-cc93-4705-a12d-209f4a2cfb53)

**Comment by qwertychouskie** [comment]
Apparently this should be fixed with https://github.com/espanso/espanso/pull/1901, but haven't been able to test this myself yet.

**Comment by opennomad** [comment]
I did a build of the `dev` branch yesterday and it does appear that the weird window is now gone.

**Comment by AucaCoyan** [comment]
Yup, this is gone in `dev`
