### ISSUE TITLE
Espanso not starting in Debian+Gnome+Wayland

### ISSUE THREAD

**Issue by ndri** [espanso/espanso#1638]
**Describe the bug**
I have never used Espanso before and it doesn't seem to be working on Debian. I have added myself to the `input` and `plugdev` groups. I have tried restarting.

**To Reproduce**
1. Start espanso

**Expected behavior**
Espanso should start.

**Logs**

Output of `espanso -vv worker`:
```
16:29:46 [worker(21859)] [DEBUG] (1) espanso_path: detected config directory in $HOME/.config/espanso
16:29:46 [worker(21859)] [DEBUG] (1) espanso_path: detected default runtime dir: "/home/work/.cache/espanso"
16:29:46 [worker(21859)] [DEBUG] (1) espanso_path: detected default packages dir: "/home/work/.config/espanso/match/packages"
16:29:46 [worker(21859)] [INFO] reading configs from: "/home/work/.config/espanso"
16:29:46 [worker(21859)] [INFO] reading packages from: "/home/work/.config/espanso/match/packages"
16:29:46 [worker(21859)] [INFO] using runtime dir: "/home/work/.cache/espanso"
16:29:46 [worker(21859)] [INFO] system info: Debian GNU/Linux v11 - kernel: 5.10.0-23-amd64
16:29:46 [worker(21859)] [DEBUG] (1) espanso_config::config::store: loaded default config at path: "/home/work/.config/espanso/config/default.yml"
16:29:46 [worker(21859)] [DEBUG] (1) espanso::patch::config_store: skipping 'alacritty_terminal_x11' patch
16:29:46 [worker(21859)] [DEBUG] (1) espanso::patch::config_store: skipping 'emacs_x11' patch
16:29:46 [worker(21859)] [DEBUG] (1) espanso::patch::config_store: skipping 'gedit_x11' patch
16:29:46 [worker(21859)] [DEBUG] (1) espanso::patch::config_store: skipping 'generic_terminal_x11' patch
16:29:46 [worker(21859)] [DEBUG] (1) espanso::patch::config_store: skipping 'kitty_terminal_x11' patch
16:29:46 [worker(21859)] [DEBUG] (1) espanso::patch::config_store: skipping 'konsole_terminal_x11' patch
16:29:46 [worker(21859)] [DEBUG] (1) espanso::patch::config_store: skipping 'libreoffice_writer_x11' patch
16:29:46 [worker(21859)] [DEBUG] (1) espanso::patch::config_store: skipping 'simple_terminal_x11' patch
16:29:46 [worker(21859)] [DEBUG] (1) espanso::patch::config_store: skipping 'simple_terminal_2_x11' patch
16:29:46 [worker(21859)] [DEBUG] (1) espanso::patch::config_store: skipping 'terminator_terminal_x11' patch
16:29:46 [worker(21859)] [DEBUG] (1) espanso::patch::config_store: skipping 'termite_terminal_x11' patch
16:29:46 [worker(21859)] [DEBUG] (1) espanso::patch::config_store: skipping 'thunderbird_x11' patch
16:29:46 [worker(21859)] [DEBUG] (1) espanso::patch::config_store: skipping 'tilix_terminal_x11' patch
16:29:46 [worker(21859)] [DEBUG] (1) espanso::patch::config_store: skipping 'urxvt_terminal_x11' patch
16:29:46 [worker(21859)] [DEBUG] (1) espanso::patch::config_store: skipping 'xterm_terminal_x11' patch
16:29:46 [worker(21859)] [DEBUG] (1) espanso::patch::config_store: skipping 'yakuake_terminal_x11' patch
16:29:46 [worker(21859)] [DEBUG] (1) espanso::patch::config_store: skipping 'virtualbox_x11' patch
16:29:46 [worker(21859)] [DEBUG] (1) espanso::cli::worker: starting with start-reason = None
16:29:46 [worker(21859)] [DEBUG] (1) espanso::icon: skipping extraction for '"/home/work/.cache/espanso/iconv2.png"', as it's already present
16:29:46 [worker(21859)] [DEBUG] (1) espanso::icon: skipping extraction for '"/home/work/.cache/espanso/search.png"', as it's already present
16:29:46 [worker(21859)] [DEBUG] (1) espanso::icon: skipping extraction for '"/home/work/.cache/espanso/icon_no_background.png"', as it's already present
16:29:46 [worker(21859)] [INFO] binded to IPC unix socket: /home/work/.cache/espanso/espansoworkerv2.sock
16:29:46 [worker(21859)] [INFO] using WaylandAppInfoProvider
16:29:46 [worker(21859)] [WARN] EVDEV backend is being used, but without enabling linux capabilities.
16:29:46 [worker(21859)] [WARN]   Although you CAN run espanso EVDEV backend as root, it's not recommended due
16:29:46 [worker(21859)] [WARN]   to security reasons. Espanso supports linux capabilities to limit the attack surface
16:29:46 [worker(21859)] [WARN]   area by only leveraging on the CAP_DAC_OVERRIDE capability (needed to work with
16:29:46 [worker(21859)] [WARN]   /dev/input/* devices to detect and inject text) and disabling it as soon as the
16:29:46 [worker(21859)] [WARN]   initial setup is completed.
16:29:46 [worker(21859)] [INFO] detection module will use this keyboard layout: [R=, M=, L=et, V=, O=]
16:29:46 [worker(21859)] [INFO] using EVDEVSource
16:29:46 [worker(21859)] [INFO] Querying modifier status...
16:29:46 [worker(21859)] [DEBUG] (4) espanso_detect::evdev: Updating device modifier state: ModifiersState { ctrl: false, alt: false, shift: false, caps_lock: false, meta: false, num_lock: false }
16:29:46 [worker(21859)] [INFO] inject module will use this keyboard layout: [R=, M=, L=et, V=, O=]
16:29:46 [worker(21859)] [INFO] using EVDEVInjector
16:29:46 [worker(21859)] [ERROR] Error: could not open uinput device
16:29:46 [worker(21859)] [ERROR] This might be due to a recent kernel update, please restart your PC so that the uinput module can be loaded correctly.
16:29:46 [worker(21859)] [ERROR] thread 'engine thread' panicked at 'failed to initialize injector module: could not open uinput device': espanso/src/cli/worker/engine/mod.rs:184
16:29:46 [worker(21859)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
16:29:46 [worker(21859)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
```

**Setup information**
- OS: Debian 11
- Kernel: 5.10.0-23-amd64
- DE: GNOME Shell 3.38.6
- Version: 2.1.8

Config file:
```
keyboard_layout:
  layout: et
```

**Comment by Vistaus** [comment]
The error clearly specifies that you haven't leveraged the capabilities, which is why you need to run

sudo setcap "cap_dac_override+p" $(which espanso)

as per the Espanso installation guide.

**Comment by ndri** [comment]
I wouldn't say "clearly specifies", but this solves my issue and Espanso works now. Thanks!

**Comment by ndri** [comment]
I wouldn't say "clearly specifies", but this solves my issue and Espanso works now. Thanks!

**Comment by Vistaus** [comment]
https://espanso.org/docs/install/linux/#wayland-compile

```
Adding the required Capabilities[​](https://espanso.org/docs/install/linux/#adding-the-required-capabilities)
Espanso requires access to the /dev/input/eventX and /dev/uinput interfaces to detect triggers and inject expansions respectively. Although you could run it as root to grant the necessary permissions, Espanso supports a safer alternative that consists in adding the CAP_DAC_OVERRIDE capability to the binary's set of Permitted ones. To do so, run the following command:

sudo setcap "cap_dac_override+p" $(which espanso)
```

It can't be any more clear. But I'm glad it's solved now! 🙂

**Comment by ndri** [comment]
I meant the error part. For the documentation, I didn't notice that there was a separate installation guide for Wayland, which led me to this confusing error.
