### ISSUE TITLE
Window "twitch" on OpenSUSE Tumbleweed using Hyprland

### ISSUE THREAD

**Issue by fearlessgeekmedia** [espanso/espanso#1649]
**Describe the bug**
I'd call it like a "twitch" of sorts.

Once I have Espanso registered (I did build it for Wayland), and running, whatever window is active will automatically "twitch" every few seconds. It seems like a window is trying to load up (probably the initial Espanso window) but is crashing. And it keeps retrying. This is my guess. 

Additionally, Espanso doesn't seem to be working.

**To Reproduce**
1. In Wayland, from the terminal, register the espanso service
2. Start espanso

**Expected behavior**
I expect the initial espanso window to open for me to test Espanso.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Logs**
22:31:48 [daemon(10763)] [INFO] reading configs from: "/home/fearlessgeek/.config/espanso"
22:31:48 [daemon(10763)] [INFO] reading packages from: "/home/fearlessgeek/.config/espanso/match/packages"
22:31:48 [daemon(10763)] [INFO] using runtime dir: "/home/fearlessgeek/.cache/espanso"
22:31:48 [daemon(10763)] [INFO] system info: openSUSE Tumbleweed v20230706 - kernel: 6.3.9-1-default
22:31:48 [daemon(10763)] [INFO] watching for changes in path: "/home/fearlessgeek/.config/espanso"
22:31:48 [daemon(10763)] [INFO] espanso version: 2.2.0
22:31:48 [daemon(10763)] [INFO] spawning the worker process...
22:31:48 [daemon(10763)] [INFO] binded to IPC unix socket: /home/fearlessgeek/.cache/espanso/espansodaemonv2.sock
22:31:48 [daemon(10763)] [WARN] keyboard layout watcher couldn't determine active layout.
22:31:48 [worker(10770)] [INFO] reading configs from: "/home/fearlessgeek/.config/espanso"
22:31:48 [worker(10770)] [INFO] reading packages from: "/home/fearlessgeek/.config/espanso/match/packages"
22:31:48 [worker(10770)] [INFO] using runtime dir: "/home/fearlessgeek/.cache/espanso"
22:31:48 [worker(10770)] [INFO] system info: openSUSE Tumbleweed v20230706 - kernel: 6.3.9-1-default
22:31:48 [worker(10770)] [INFO] binded to IPC unix socket: /home/fearlessgeek/.cache/espanso/espansoworkerv2.sock
22:31:48 [worker(10770)] [INFO] using WaylandAppInfoProvider
22:31:48 [worker(10770)] [INFO] monitoring the status of the daemon process
22:31:48 [worker(10770)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
22:31:48 [worker(10770)] [INFO] using EVDEVSource
22:31:49 [worker(10770)] [INFO] Querying modifier status...
22:31:49 [worker(10770)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
22:31:49 [worker(10770)] [INFO] using EVDEVInjector
22:31:49 [worker(10770)] [INFO] using WaylandFallbackClipboard
22:31:49 [worker(10770)] [ERROR] unable to call 'wl-paste' binary, please install the wl-clipboard package.
22:31:49 [worker(10770)] [ERROR] thread 'engine thread' panicked at 'failed to initialize clipboard module: wl-clipboard binaries are missing': espanso/src/cli/worker/engine/mod.rs:186
22:31:49 [worker(10770)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
22:31:49 [worker(10770)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
22:31:49 [daemon(10763)] [ERROR] received unexpected exit code from worker 101, exiting
fearlessgeek@localhost:~> espanso stop && espanso service unregister

**Setup information**
- OS: OpenSUSE Tumbleweed
- Version: Latest (github)

**Comment by fearlessgeekmedia** [comment]
Actually I just realized I need to install wl-clipboard so I'm trying that. Yep, that did the trick!
