### ISSUE TITLE
Unusable in Wayland

### ISSUE THREAD

**Issue by Yubo-Cao** [espanso/espanso#1750]
**Describe the bug**
Whenever I attempt to start Espanso daemon by `espanso daemon`, it would automatically quits and perform nothing.

**To Reproduce**
1. run `espanso daemon`

**Expected behavior**
I would expect `espanso daemon` to stay and keep running so that I could use it.

**Logs**
```
16:30:29 [daemon(376196)] [INFO] reading configs from: "/home/yubo/.config/espanso"
16:30:29 [daemon(376196)] [INFO] reading packages from: "/home/yubo/.config/espanso/match/packages"
16:30:29 [daemon(376196)] [INFO] using runtime dir: "/home/yubo/.cache/espanso"
16:30:29 [daemon(376196)] [INFO] system info: NixOS v23.11 - kernel: 6.5.11-xanmod1
16:30:29 [daemon(376196)] [WARN] keyboard layout watcher couldn't determine active layout.
16:30:29 [daemon(376196)] [INFO] watching for changes in path: "/home/yubo/.config/espanso"
16:30:29 [daemon(376196)] [INFO] espanso version: 2.1.8
16:30:29 [daemon(376196)] [INFO] spawning the worker process...
16:30:29 [daemon(376196)] [INFO] binded to IPC unix socket: /home/yubo/.cache/espanso/espansodaemonv2.sock
16:30:29 [worker(376205)] [INFO] reading configs from: "/home/yubo/.config/espanso"
16:30:29 [worker(376205)] [INFO] reading packages from: "/home/yubo/.config/espanso/match/packages"
16:30:29 [worker(376205)] [INFO] using runtime dir: "/home/yubo/.cache/espanso"
16:30:29 [worker(376205)] [INFO] system info: NixOS v23.11 - kernel: 6.5.11-xanmod1
16:30:29 [worker(376205)] [INFO] binded to IPC unix socket: /home/yubo/.cache/espanso/espansoworkerv2.sock
16:30:29 [worker(376205)] [INFO] using WaylandAppInfoProvider
16:30:29 [worker(376205)] [WARN] EVDEV backend is being used, but without enabling linux capabilities.
16:30:29 [worker(376205)] [WARN]   Although you CAN run espanso EVDEV backend as root, it's not recommended due
16:30:29 [worker(376205)] [WARN]   to security reasons. Espanso supports linux capabilities to limit the attack surface
16:30:29 [worker(376205)] [WARN]   area by only leveraging on the CAP_DAC_OVERRIDE capability (needed to work with
16:30:29 [worker(376205)] [WARN]   /dev/input/* devices to detect and inject text) and disabling it as soon as the
16:30:29 [worker(376205)] [WARN]   initial setup is completed.
16:30:29 [worker(376205)] [INFO] monitoring the status of the daemon process
16:30:29 [worker(376205)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
16:30:29 [worker(376205)] [INFO] using EVDEVSource
16:30:29 [worker(376205)] [INFO] Querying modifier status...
interface 'wl_surface' has no event 2
16:30:29 [worker(376205)] [ERROR] thread 'detect thread' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 0, kind: Uncategorized, message: "Success" }': espanso-detect/src/evdev/sync/wayland.rs:193
warning: queue 0x7fc8a4038f60 destroyed while proxies still attached:
  zwp_primary_selection_offer_v1@4278190082 still attached
  zwp_primary_selection_offer_v1@4278190081 still attached
  wl_data_offer@4278190080 still attached
  wl_buffer@24 still attached
  wl_keyboard@23 still attached
  xdg_wm_base@15 still attached
  wl_surface@14 still attached
  zwp_primary_selection_device_v1@13 still attached
  zwp_primary_selection_device_manager_v1@3 still attached
  wl_data_device@12 still attached
  wl_output@11 still attached
  wl_output@10 still attached
  zxdg_decoration_manager_v1@9 still attached
  wl_seat@8 still attached
  wl_data_device_manager@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached
16:30:29 [worker(376205)] [ERROR] thread 'engine thread' panicked at 'unable to receive from the init_rx channel: RecvError': espanso/src/cli/worker/engine/funnel/mod.rs:124
16:30:29 [worker(376205)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
16:30:29 [worker(376205)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
16:30:29 [daemon(376196)] [ERROR] received unexpected exit code from worker 101, exiting
```
**Setup information**
- OS: `Linux yix 6.5.11-xanmod1 #1-NixOS SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980 x86_64 GNU/Linux`
- Version: `espanso 2.1.8`

**Comment by smeech** [comment]
Have you tried setting the keyboard layout as suggested in the above log? Instructions at https://espanso.org/docs/configuration/options/#options-reference

**Comment by Yubo-Cao** [comment]
Sadly, this doesn't seem to help. Below is the log file after including `layout: us` in the configuration file.
```
14:20:45 [daemon(1851254)] [INFO] reading configs from: "/home/yubo/.config/espanso"
14:20:45 [daemon(1851254)] [INFO] reading packages from: "/home/yubo/.config/espanso/match/packages"
14:20:45 [daemon(1851254)] [INFO] using runtime dir: "/home/yubo/.cache/espanso"
14:20:45 [daemon(1851254)] [INFO] system info: NixOS v23.11 - kernel: 6.5.11-xanmod1
14:20:45 [daemon(1851254)] [WARN] keyboard layout watcher couldn't determine active layout.
14:20:45 [daemon(1851254)] [INFO] espanso version: 2.1.8
14:20:45 [daemon(1851254)] [INFO] watching for changes in path: "/home/yubo/.config/espanso"
14:20:45 [daemon(1851254)] [INFO] spawning the worker process...
14:20:45 [daemon(1851254)] [INFO] binded to IPC unix socket: /home/yubo/.cache/espanso/espansodaemonv2.sock
14:20:45 [worker(1851263)] [INFO] reading configs from: "/home/yubo/.config/espanso"
14:20:45 [worker(1851263)] [INFO] reading packages from: "/home/yubo/.config/espanso/match/packages"
14:20:45 [worker(1851263)] [INFO] using runtime dir: "/home/yubo/.cache/espanso"
14:20:45 [worker(1851263)] [INFO] system info: NixOS v23.11 - kernel: 6.5.11-xanmod1
14:20:45 [worker(1851263)] [INFO] binded to IPC unix socket: /home/yubo/.cache/espanso/espansoworkerv2.sock
14:20:45 [worker(1851263)] [INFO] using WaylandAppInfoProvider
14:20:45 [worker(1851263)] [INFO] monitoring the status of the daemon process
14:20:45 [worker(1851263)] [WARN] EVDEV backend is being used, but without enabling linux capabilities.
14:20:45 [worker(1851263)] [WARN]   Although you CAN run espanso EVDEV backend as root, it's not recommended due
14:20:45 [worker(1851263)] [WARN]   to security reasons. Espanso supports linux capabilities to limit the attack surface
14:20:45 [worker(1851263)] [WARN]   area by only leveraging on the CAP_DAC_OVERRIDE capability (needed to work with
14:20:45 [worker(1851263)] [WARN]   /dev/input/* devices to detect and inject text) and disabling it as soon as the
14:20:45 [worker(1851263)] [WARN]   initial setup is completed.
14:20:45 [worker(1851263)] [INFO] detection module will use this keyboard layout: [R=, M=, L=us, V=, O=]
14:20:45 [worker(1851263)] [INFO] using EVDEVSource
14:20:45 [worker(1851263)] [INFO] Querying modifier status...
interface 'wl_surface' has no event 2
14:20:45 [worker(1851263)] [ERROR] thread 'detect thread' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 0, kind: Uncategorized, message: "Success" }': espanso-detect/src/evdev/sync/wayland.rs:193
warning: queue 0x7f3c94038f60 destroyed while proxies still attached:
  zwp_primary_selection_offer_v1@4278190082 still attached
  zwp_primary_selection_offer_v1@4278190081 still attached
  wl_data_offer@4278190080 still attached
  wl_buffer@24 still attached
  wl_keyboard@23 still attached
  xdg_wm_base@15 still attached
  wl_surface@14 still attached
  zwp_primary_selection_device_v1@13 still attached
  zwp_primary_selection_device_manager_v1@3 still attached
  wl_data_device@12 still attached
  wl_output@11 still attached
  wl_output@10 still attached
  zxdg_decoration_manager_v1@9 still attached
  wl_seat@8 still attached
  wl_data_device_manager@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached
14:20:45 [worker(1851263)] [ERROR] thread 'engine thread' panicked at 'unable to receive from the init_rx channel: RecvError': espanso/src/cli/worker/engine/funnel/mod.rs:124
14:20:45 [worker(1851263)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
14:20:45 [worker(1851263)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
14:20:45 [daemon(1851254)] [ERROR] received unexpected exit code from worker 101, exiting
```

**Comment by smeech** [comment]
Is that a typo for `keyboard_layout`?

**Comment by smeech** [comment]
I didn't use `espanso daemon ` but followed the instructions at https://espanso.org/docs/install/linux/#install-on-wayland strictly.

If I stop espanso and then type `espanso daemon` I get the following log output, in case it helps:
```
19:50:55 [daemon(69653)] [INFO] reading configs from: "/home/stephen/.config/espanso"
19:50:55 [daemon(69653)] [INFO] reading packages from: "/home/stephen/.config/espanso/match/packages"
19:50:55 [daemon(69653)] [INFO] using runtime dir: "/home/stephen/.cache/espanso"
19:50:55 [daemon(69653)] [INFO] system info: Fedora Linux v39 - kernel: 6.5.11-300.fc39.x86_64
19:50:55 [daemon(69653)] [INFO] espanso version: 2.2.0
19:50:55 [daemon(69653)] [INFO] watching for changes in path: "/home/stephen/.config/espanso"
19:50:55 [daemon(69653)] [INFO] spawning the worker process...
19:50:55 [daemon(69653)] [INFO] binded to IPC unix socket: /home/stephen/.cache/espanso/espansodaemonv2.sock
19:50:55 [daemon(69653)] [WARN] keyboard layout watcher couldn't determine active layout.
19:50:55 [worker(69660)] [INFO] reading configs from: "/home/stephen/.config/espanso"
19:50:55 [worker(69660)] [INFO] reading packages from: "/home/stephen/.config/espanso/match/packages"
19:50:55 [worker(69660)] [INFO] using runtime dir: "/home/stephen/.cache/espanso"
19:50:55 [worker(69660)] [INFO] system info: Fedora Linux v39 - kernel: 6.5.11-300.fc39.x86_64
19:50:55 [worker(69660)] [INFO] binded to IPC unix socket: /home/stephen/.cache/espanso/espansoworkerv2.sock
19:50:55 [worker(69660)] [INFO] using WaylandAppInfoProvider
19:50:55 [worker(69660)] [INFO] monitoring the status of the daemon process
19:50:55 [worker(69660)] [INFO] detection module will use this keyboard layout: [R=, M=, L=gb, V=, O=]
19:50:55 [worker(69660)] [INFO] using EVDEVSource
19:50:55 [worker(69660)] [INFO] Querying modifier status...
warning: queue 0x7ff218039140 destroyed while proxies still attached:
  wl_buffer@31 still attached
  wl_buffer@36 still attached
  wl_buffer@32 still attached
  wl_buffer@33 still attached
  wl_buffer@35 still attached
  wl_buffer@34 still attached
  zwp_primary_selection_offer_v1@4278190081 still attached
  wl_data_offer@4278190080 still attached
  wl_keyboard@30 still attached
  wl_subsurface@24 still attached
  wl_surface@23 still attached
  wl_subsurface@22 still attached
  wl_surface@21 still attached
  wl_subsurface@20 still attached
  wl_surface@19 still attached
  wl_subsurface@18 still attached
  wl_surface@17 still attached
  wl_subsurface@16 still attached
  wl_surface@15 still attached
  xdg_wm_base@13 still attached
  wl_surface@12 still attached
  zwp_primary_selection_device_v1@11 still attached
  zwp_primary_selection_device_manager_v1@3 still attached
  wl_data_device@10 still attached
  wl_seat@9 still attached
  wl_subcompositor@8 still attached
  wl_data_device_manager@7 still attached
  wl_output@6 still attached
  wl_shm@5 still attached
  wl_compositor@4 still attached
  wl_registry@2 still attached
19:50:56 [worker(69660)] [INFO] inject module will use this keyboard layout: [R=, M=, L=gb, V=, O=]
19:50:56 [worker(69660)] [INFO] using EVDEVInjector
19:50:56 [worker(69660)] [INFO] using WaylandFallbackClipboard
```

**Comment by Yubo-Cao** [comment]
It seems that `espanso start` does no work anyway.
```bash
> espanso start --unmanaged
espanso started correctly!
> pgrep espanso # return nothing
```
And also, since I am using NixOS, the executable `espanso` is read-only. Therefore, it's possible to grant such capability to espanso and test if it works unless I repackage this package entirely.

**Comment by smeech** [comment]
Have you tried registering is as a systemd service, or doesn't that apply to you?

**Comment by Yubo-Cao** [comment]
Systemd service is mere `espanso daemon` (provided by the distribution's package manager by default). Therefore, it doesn't work either. Below is the output of running `journalctl --user -xeu espanso`
```
Nov 21 15:36:00 yix espanso[2215608]: 15:36:00 [daemon(2215608)] [INFO] reading configs from: "/home/yubo/.config/espanso"
Nov 21 15:36:00 yix espanso[2215608]: 15:36:00 [daemon(2215608)] [INFO] reading packages from: "/home/yubo/.config/espanso/match/packages"
Nov 21 15:36:00 yix espanso[2215608]: 15:36:00 [daemon(2215608)] [INFO] using runtime dir: "/home/yubo/.cache/espanso"
Nov 21 15:36:00 yix espanso[2215608]: 15:36:00 [daemon(2215608)] [INFO] system info: NixOS v23.11 - kernel: 6.5.11-xanmod1
Nov 21 15:36:00 yix espanso[2215608]: 15:36:00 [daemon(2215608)] [WARN] keyboard layout watcher couldn't determine active layout.
Nov 21 15:36:00 yix espanso[2215608]: 15:36:00 [daemon(2215608)] [INFO] watching for changes in path: "/home/yubo/.config/espanso"
Nov 21 15:36:00 yix espanso[2215608]: 15:36:00 [daemon(2215608)] [INFO] espanso version: 2.1.8
Nov 21 15:36:00 yix espanso[2215608]: 15:36:00 [daemon(2215608)] [INFO] spawning the worker process...
Nov 21 15:36:00 yix espanso[2215608]: 15:36:00 [daemon(2215608)] [INFO] binded to IPC unix socket: /home/yubo/.cache/espanso/espansodaemonv2.sock
Nov 21 15:36:00 yix espanso[2215614]: 15:36:00 [worker(2215614)] [INFO] reading configs from: "/home/yubo/.config/espanso"
Nov 21 15:36:00 yix espanso[2215614]: 15:36:00 [worker(2215614)] [INFO] reading packages from: "/home/yubo/.config/espanso/match/packages"
Nov 21 15:36:00 yix espanso[2215614]: 15:36:00 [worker(2215614)] [INFO] using runtime dir: "/home/yubo/.cache/espanso"
Nov 21 15:36:00 yix espanso[2215614]: 15:36:00 [worker(2215614)] [INFO] system info: NixOS v23.11 - kernel: 6.5.11-xanmod1
Nov 21 15:36:00 yix espanso[2215614]: 15:36:00 [worker(2215614)] [INFO] binded to IPC unix socket: /home/yubo/.cache/espanso/espansoworkerv2.sock
Nov 21 15:36:00 yix espanso[2215614]: 15:36:00 [worker(2215614)] [INFO] using WaylandAppInfoProvider
Nov 21 15:36:00 yix espanso[2215614]: 15:36:00 [worker(2215614)] [WARN] EVDEV backend is being used, but without enabling linux capabilities.
Nov 21 15:36:00 yix espanso[2215614]: 15:36:00 [worker(2215614)] [WARN]   Although you CAN run espanso EVDEV backend as root, it's not recommended due
Nov 21 15:36:00 yix espanso[2215614]: 15:36:00 [worker(2215614)] [WARN]   to security reasons. Espanso supports linux capabilities to limit the attac>
Nov 21 15:36:00 yix espanso[2215614]: 15:36:00 [worker(2215614)] [WARN]   area by only leveraging on the CAP_DAC_OVERRIDE capability (needed to work >
Nov 21 15:36:00 yix espanso[2215614]: 15:36:00 [worker(2215614)] [WARN]   /dev/input/* devices to detect and inject text) and disabling it as soon as>
Nov 21 15:36:00 yix espanso[2215614]: 15:36:00 [worker(2215614)] [INFO] monitoring the status of the daemon process
Nov 21 15:36:00 yix espanso[2215614]: 15:36:00 [worker(2215614)] [WARN]   initial setup is completed.
Nov 21 15:36:00 yix espanso[2215614]: 15:36:00 [worker(2215614)] [INFO] detection module will use this keyboard layout: [R=, M=, L=us, V=, O=]
Nov 21 15:36:00 yix espanso[2215614]: 15:36:00 [worker(2215614)] [INFO] using EVDEVSource
Nov 21 15:36:00 yix espanso[2215614]: 15:36:00 [worker(2215614)] [INFO] Querying modifier status...
Nov 21 15:36:00 yix espanso[2215614]: interface 'wl_surface' has no event 2
Nov 21 15:36:00 yix espanso[2215614]: 15:36:00 [worker(2215614)] [ERROR] thread 'detect thread' panicked at 'called `Result::unwrap()` on an `Err` va>
Nov 21 15:36:00 yix espanso[2215614]: warning: queue 0x7fa5d0038f60 destroyed while proxies still attached:
Nov 21 15:36:00 yix espanso[2215614]:   zwp_primary_selection_offer_v1@4278190082 still attached
Nov 21 15:36:00 yix espanso[2215614]:   zwp_primary_selection_offer_v1@4278190081 still attached
Nov 21 15:36:00 yix espanso[2215614]:   wl_data_offer@4278190080 still attached
Nov 21 15:36:00 yix espanso[2215614]:   wl_buffer@24 still attached
Nov 21 15:36:00 yix espanso[2215614]:   wl_keyboard@23 still attached
Nov 21 15:36:00 yix espanso[2215614]:   xdg_wm_base@15 still attached
Nov 21 15:36:00 yix espanso[2215614]:   wl_surface@14 still attached
Nov 21 15:36:00 yix espanso[2215614]:   zwp_primary_selection_device_v1@13 still attached
Nov 21 15:36:00 yix espanso[2215614]:   zwp_primary_selection_device_manager_v1@3 still attached
Nov 21 15:36:00 yix espanso[2215614]:   wl_data_device@12 still attached
Nov 21 15:36:00 yix espanso[2215614]:   wl_output@11 still attached
Nov 21 15:36:00 yix espanso[2215614]:   wl_output@10 still attached
Nov 21 15:36:00 yix espanso[2215614]:   zxdg_decoration_manager_v1@9 still attached
Nov 21 15:36:00 yix espanso[2215614]:   wl_seat@8 still attached
Nov 21 15:36:00 yix espanso[2215614]:   wl_data_device_manager@7 still attached
Nov 21 15:36:00 yix espanso[2215614]:   wl_subcompositor@6 still attached
Nov 21 15:36:00 yix espanso[2215614]:   wl_compositor@5 still attached
Nov 21 15:36:00 yix espanso[2215614]:   wl_shm@4 still attached
Nov 21 15:36:00 yix espanso[2215614]:   wl_registry@2 still attached
Nov 21 15:36:00 yix espanso[2215614]: 15:36:00 [worker(2215614)] [ERROR] thread 'engine thread' panicked at 'unable to receive from the init_rx chann>
Nov 21 15:36:00 yix espanso[2215614]: 15:36:00 [worker(2215614)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected c>
Nov 21 15:36:00 yix espanso[2215614]: 15:36:00 [worker(2215614)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an emp>
Nov 21 15:36:00 yix espanso[2215608]: 15:36:00 [daemon(2215608)] [ERROR] received unexpected exit code from worker 101, exiting
Nov 21 15:36:00 yix systemd[2920]: espanso.service: Main process exited, code=exited, status=101/n/a
```

**Comment by morgan-dgk** [comment]
Also seeing this on Arch 6.6.4 / Hyprland 0.33.1. It was working yesterday, but will no longer start (crashes with the same error, `wl_surface has no event 2`). Possibly related to this [issue](https://github.com/wez/wezterm/issues/3996) from a separate project, since espanso-detect has a dependency on smithay-client-toolkit 15.4 when built for wayland. 

Rolling back to Hyprland 0.30 resolves this issue. This leads to me conclude that the issue is probably lies in the recent commits to wlroots which Hyprland / other Wayland compositors presumably depend on.  

It may be necessary to upgrade the smithay-client-toolkit dependency to ensure comptability with Wayland, but I am no expert here.
