### ISSUE TITLE
thread 'main' panicked at 'unable to load config: unable to load config

### ISSUE THREAD

**Issue by drfurtado** [espanso/espanso#1787]
**Describe the bug**
I get the following message when trying to set up synchronization with Dropbox

When I type `espanso path config` in the terminal, I get the following error:

```
thread 'main' panicked at 'unable to load config: unable to load config

Caused by:
    missing config directory', espanso/src/main.rs:594:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ovandef@Ovandes-MacBook-Pro ~ % 
```

**To Reproduce**
1. type espanso path config into the terminal after installing espanso

**Setup information**
- OS: MacOS Ventura 13.6.1
- Version:2.1.8

**Comment by atopheim** [comment]
Got the same error on manjaro following this guide: https://espanso.org/docs/install/linux/ at `espanso -vv worker`

**Comment by jope35** [comment]
also get this error when following the [guide](https://espanso.org/docs/sync/#macos) on macos 14.3.1 (23D60) and espanso version: 2.2.1  

```
thread 'main' panicked at espanso-path/src/lib.rs:48:33:
unable to create config directory: Os { code: 17, kind: AlreadyExists, message: "File exists" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by morgan-dgk** [comment]
@jope35 this is a different error, probably a duplicate of #1909. For some reason, Espanso is failing to find the existing config directory. I will try and look into this, but do not have a Mac for testing purpose.

**Comment by jope35** [comment]
> @jope35 this is a different error, probably a duplicate of #1909. For some reason, Espanso is failing to find the existing config directory. I will try and look into this, but do not have a Mac for testing purpose.

Hi @morgan-dgk I have a mac and more than happy to help with testing, feel free to send me a DM

**Comment by morgan-dgk** [comment]
Hey @jope35, can you run `espanso log` or `espanso -vvvvv worker` in your terminal and share the output here? You should see a line like `INFO:creating config directory in <config_dir>`. 

If Espanso is using the default config path, this should be at `$HOME/Library/Application Support/espanso.` If this is the case, can you please try moving the existing symlinked folder outside of the Application Support Folder? Before doing so, please make sure you run `espanso stop` in the cli to ensure Espanso is not running. Espanso should then be able to create the necessary config folder. 

My initial hunch was that the symlinked config directory might be the culprit, but the library function espanso is using to get the config directory seems like it should handle symlinks without issue.

**Comment by jope35** [comment]
Hi @morgan-dgk,Thank you for the prompt response. I have identified the cause of the error; in the symlink, I incorrectly used `~` instead of `$HOME`, what is specified in the documentation. 🙈

**Comment by morgan-dgk** [comment]
@drfurtado, apologies for slow reply. Is this still an issue for you?

**Comment by turbits** [comment]
Hey all, I can confirm that this is still happening. I installed espanso with homebrew `brew install espanso`, tried running `espanso path`, and got the following:

```txt
thread 'main' panicked at espanso/src/main.rs:594:55:
unable to load config: unable to load config

Caused by:
    missing config directory
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I ran it with full backtrace after 1 didn't seem to show much, don't know if this is helpful I've not used rust and not very familiar with Mac:

```txt
thread 'main' panicked at espanso/src/main.rs:594:55:
unable to load config: unable to load config

Caused by:
    missing config directory
stack backtrace:
   0:        0x100b486f8 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0524bd1b527203b8
   1:        0x100b6b44c - core::fmt::write::h74be1333b0a6ddea
   2:        0x100b443e4 - std::io::Write::write_fmt::h6c011b665b2d7d4b
   3:        0x100b48538 - std::sys_common::backtrace::print::he25ff7dac6402434
   4:        0x100b4a0e0 - std::panicking::default_hook::{{closure}}::h41763ba018b93bf7
   5:        0x100b49df8 - std::panicking::default_hook::h017c44660373840e
   6:        0x100b4a624 - std::panicking::rust_panic_with_hook::h221a0baf52ecd48a
   7:        0x100b4a52c - std::panicking::begin_panic_handler::{{closure}}::h18b661cf0f97a414
   8:        0x100b48b84 - std::sys_common::backtrace::__rust_end_short_backtrace::h4f4b2ffab2311217
   9:        0x100b4a298 - _rust_begin_unwind
  10:        0x100be4118 - core::panicking::panic_fmt::hd6070cd222575be5
  11:        0x100be4470 - core::result::unwrap_failed::h54ffffcb65858936
  12:        0x100553604 - core::result::Result<T,E>::expect::hb97b4677a42cfc6f
  13:        0x1005615bc - espanso::main::h4f215eae7af6f3e5
  14:        0x100532bb8 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbaf09f8b7e5ef771
  15:        0x100531524 - std::rt::lang_start::{{closure}}::h11d3885f4f0e593d
  16:        0x100b3d974 - std::rt::lang_start_internal::h5f00c09289a72e67
  17:        0x100562a90 - _main
```

I found the config directory from the docs, and manually made the `.../Application Support/espanso/config` folder and `default.yml` inside it, although obviously the yml file is empty. This worked, and now `espanso path` shows me my config, packages, and runtime paths. Not sure what the defaults are supposed to look like though :^)

edit, system info:
- macOS: Sequoia 15.3.1 / M4
- espanso: 2.2.1

edit 2, update: I created a match and after running initial setup from the app it works just fine, default.yml contents not required it seems 👍🏻

**Comment by JerryLerman** [comment]
I'm getting this on Ubuntu 24.04.3

2025-08-26T15:11:53.528200-04:00 Starfleet-Engineering espanso[718578]: [ERROR] thread 'engine thread' panicked at 'failed to initialize detector module: detection source initialization failed'

2025-08-26T15:11:53.749771-04:00 Starfleet-Engineering espanso[718525]: thread 'main' panicked at 'failed to launch daemon: unexpected error, 'espanso daemon' returned a non-zero exit code.', espanso/src/cli/launcher/mod.rs:213:45

2025-08-26T15:11:53.751877-04:00 Starfleet-Engineering systemd[718503]: espanso.service: Main process exited, code=exited, status=101/n/a

Then there's a cascade of app failures, and the desktop crashes.

**Comment by egigoka** [comment]
Workaround is to install Espanso 2.1.8, start app, complete introduction wizard, and re-install latest version (2.2.7 as of writing)

Worked on macOS Tahoe 26.0

**Comment by nickorr** [comment]
Just following up on this, I had the same issue on my Mac.  And the command above showed the issue:

```
$ espanso -vvvvv worker
08:24:36 [worker(53645)] [INFO] creating config directory in /Users/nick/Library/Application Support/espanso
08:24:36 [worker(53645)] [ERROR] thread 'main' panicked at 'unable to create config directory: Os { code: 17, kind: AlreadyExists, message: "File exists" }': espanso/src/path/mod.rs:75
```

When I went to the Application Support folder and double clicked the alias macOS reported that it was broken, and to try to re-point it.  But doing that also failed.   Even `espanso path config` would just error and not report anything at all.

Solution was to delete the alias at that path and recreate it.  Hope that helps someone else.

So the solution is there needs to be some extra error checking on startup that it can see what's in the folder, and trap on that error on creation and alert or similar.

Cheers,
Nick

**Comment by sauron918** [comment]
Same problem, `espanso path` gives `unable to load config: unable to load config` after `brew install --cask espanso` on macOS Sequoia
