### ISSUE TITLE
espanso 2.0.4-alpha, Debian 11, Wayland: high CPU usage

### ISSUE THREAD

**Issue by neilzone** [espanso/espanso#836]
Since installing the alpha, I've noticed the battery life on my machine is significantly less.

Running `top`, espanso is permanently at the top, with between 99.7 and 100% CPU utilisation.

With the slightly different `ps -eo pcpu,pid,user,args | sort -k1 -r -n | head -10`, espanso is again at the top:

```
48.8   49130 neil     /usr/local/bin/espanso worker --monitor-daemon
```

**Comment by federico-terzi** [comment]
Hey @neilzone,

Thanks for reporting this issue! A couple of things to debug this further:

* Does Espanso go to 100% CPU right from the start, or after a while?
* Could you please post the output of `espanso log` here?
* Could you please post the output of `ls -la /dev/input/` here? (might require root permissions)

Cheers :)

**Comment by neilzone** [comment]
> * Does Espanso go to 100% CPU right from the start, or after a while?

I've rebooted, and it is not showing on the top ten list, so perhaps only "after a while", or after some specific event.
 
> * Could you please post the output of `espanso log` here?

```
18:13:41 [daemon(2915)] [INFO] reading configs from: "/home/neil/.config/espanso"
18:13:41 [daemon(2915)] [INFO] reading packages from: "/home/neil/.config/espanso/match/packages"
18:13:41 [daemon(2915)] [INFO] using runtime dir: "/home/neil/.local/share/espanso"
18:13:41 [daemon(2915)] [INFO] espanso version: 2.0.4-alpha
18:13:41 [daemon(2915)] [INFO] spawning the worker process...
18:13:41 [daemon(2915)] [INFO] watching for changes in path: "/home/neil/.config/espanso"
18:13:41 [daemon(2915)] [INFO] binded to IPC unix socket: /home/neil/.local/share/espanso/espansodaemonv2.sock
18:13:41 [worker(2921)] [INFO] reading configs from: "/home/neil/.config/espanso"
18:13:41 [worker(2921)] [INFO] reading packages from: "/home/neil/.config/espanso/match/packages"
18:13:41 [worker(2921)] [INFO] using runtime dir: "/home/neil/.local/share/espanso"
18:13:41 [worker(2921)] [INFO] binded to IPC unix socket: /home/neil/.local/share/espanso/espansoworkerv2.sock
18:13:41 [worker(2921)] [INFO] using WaylandAppInfoProvider
18:13:41 [worker(2921)] [INFO] monitoring the status of the daemon process
18:13:41 [worker(2921)] [INFO] detection module will use this keyboard layout: [R=, M=, L=gb, V=, O=]
18:13:41 [worker(2921)] [INFO] using EVDEVSource
18:13:42 [worker(2921)] [INFO] Querying modifier status...
18:13:42 [worker(2921)] [INFO] inject module will use this keyboard layout: [R=, M=, L=gb, V=, O=]
18:13:42 [worker(2921)] [INFO] using EVDEVInjector
18:13:43 [worker(2921)] [INFO] using WaylandFallbackClipboard
18:14:12 [service(3593)] [INFO] reading configs from: "/home/neil/.config/espanso"
18:14:12 [service(3593)] [INFO] reading packages from: "/home/neil/.config/espanso/match/packages"
18:14:12 [service(3593)] [INFO] using runtime dir: "/home/neil/.local/share/espanso"
18:14:12 [service(3593)] [INFO] espanso is running
18:14:45 [worker(2921)] [WARN] rendering was aborted by extension: form, on var: form1

```

(This is when espanso is *not* showing in the top ten high CPU.


> * Could you please post the output of `ls -la /dev/input/` here? (might require root permissions)

```
total 0
drwxr-xr-x  4 root root      840 Nov  1 18:13 .
drwxr-xr-x 24 root root     5280 Nov  1 18:13 ..
drwxr-xr-x  2 root root      120 Nov  1 18:13 by-id
drwxr-xr-x  2 root root      180 Nov  1 18:13 by-path
crw-rw----  1 root input 13,  64 Nov  1 18:13 event0
crw-rw----  1 root input 13,  65 Nov  1 18:13 event1
crw-rw----  1 root input 13,  74 Nov  1 18:13 event10
crw-rw----  1 root input 13,  75 Nov  1 18:13 event11
crw-rw----  1 root input 13,  76 Nov  1 18:13 event12
crw-rw----  1 root input 13,  77 Nov  1 18:13 event13
crw-rw----  1 root input 13,  78 Nov  1 18:13 event14
crw-rw----  1 root input 13,  79 Nov  1 18:13 event15
crw-rw----  1 root input 13,  80 Nov  1 18:13 event16
crw-rw----  1 root input 13,  81 Nov  1 18:13 event17
crw-rw----  1 root input 13,  82 Nov  1 18:13 event18
crw-rw----  1 root input 13,  83 Nov  1 18:13 event19
crw-rw----  1 root input 13,  66 Nov  1 18:13 event2
crw-rw----  1 root input 13,  84 Nov  1 18:13 event20
crw-rw----  1 root input 13,  85 Nov  1 18:13 event21
crw-rw----  1 root input 13,  86 Nov  1 18:13 event22
crw-rw----  1 root input 13,  87 Nov  1 18:13 event23
crw-rw----  1 root input 13,  88 Nov  1 18:13 event24
crw-rw----  1 root input 13,  89 Nov  1 18:13 event25
crw-rw----  1 root input 13, 256 Nov  1 18:13 event256
crw-rw----  1 root input 13,  90 Nov  1 18:13 event26
crw-rw----  1 root input 13,  91 Nov  1 18:13 event27
crw-rw----  1 root input 13,  92 Nov  1 18:13 event28
crw-rw----  1 root input 13,  93 Nov  1 18:13 event29
crw-rw----  1 root input 13,  67 Nov  1 18:13 event3
crw-rw----  1 root input 13,  94 Nov  1 18:13 event30
crw-rw----  1 root input 13,  95 Nov  1 18:13 event31
crw-rw----  1 root input 13,  68 Nov  1 18:13 event4
crw-rw----  1 root input 13,  69 Nov  1 18:13 event5
crw-rw----  1 root input 13,  70 Nov  1 18:13 event6
crw-rw----  1 root input 13,  71 Nov  1 18:13 event7
crw-rw----  1 root input 13,  72 Nov  1 18:13 event8
crw-rw----  1 root input 13,  73 Nov  1 18:13 event9
crw-rw----  1 root input 13,  63 Nov  1 18:13 mice
crw-rw----  1 root input 13,  32 Nov  1 18:13 mouse0
crw-rw----  1 root input 13,  33 Nov  1 18:13 mouse1
crw-rw----  1 root input 13,  34 Nov  1 18:13 mouse2
crw-rw----  1 root input 13,  35 Nov  1 18:13 mouse3
```

**Comment by neilzone** [comment]
I might have caught it: it suddenly spikes in CPU, and the log is filled with these lines:

```
18:14:45 [worker(2921)] [WARN] rendering was aborted by extension: form, on var: form1
18:30:59 [worker(2921)] [ERROR] Can't read from device /dev/input/event4: read operation can't block device
18:30:59 [worker(2921)] [ERROR] Can't read from device /dev/input/event4: read operation can't block device
18:30:59 [worker(2921)] [ERROR] Can't read from device /dev/input/event4: read operation can't block device
```
(It spawns hundreds of these lines per second.)

**Comment by federico-terzi** [comment]
Hey @neilzone,

I've investigated a bit and I was able to reproduce the problem on my machine. That happened when unplugging the keyboard (at least in my case).
I've pushed a fix on the `dev` branch, when you have the chance could you please try to pull the latest changes from there, recompile espanso and see if that helps?

As a side note, I've realized the current Wayland backend won't be able to detect when a new keyboard is plugged in. So you'll need to run `espanso restart` manually after plugging a new device if needed

Cheers :)

**Comment by neilzone** [comment]
> That happened when unplugging the keyboard (at least in my case).

I’ll try it - thanks!

I am using a Microsoft Surface, which has both a physical keyboard, and an onscreen virtual keyboard. But I don’t recall triggering the virtual keyboard, so perhaps something to do with the physical keyboard, and perhaps some kind of power saving mode. I’ll have a play around.

**Comment by neilzone** [comment]
> I've pushed a fix on the `dev` branch, when you have the chance could you please try to pull the latest changes from there, recompile espanso and see if that helps?

I've compiled it, and it seemed to build fine.


I have double-checked I have run:

```
sudo setcap "cap_dac_override+p" /home/neil/Downloads/espanso_wayland/espanso/target/release/espanso
```

and then moved the binary to `/usr/local/bin/espanso`.


Running `espanso --version` shows:

> espanso 2.0.5-alpha

which looks right.

However, while `espanso start` reports:

> espanso started correctly!

 `espanso status` returns:

>espanso is not running

Here's the log:

```
08:42:17 [daemon(253845)] [INFO] reading configs from: "/home/neil/.config/espanso"
08:42:17 [daemon(253845)] [INFO] reading packages from: "/home/neil/.config/espanso/match/packages"
08:42:17 [daemon(253845)] [INFO] using runtime dir: "/home/neil/.local/share/espanso"
08:42:17 [daemon(253845)] [INFO] watching for changes in path: "/home/neil/.config/espanso"
08:42:17 [daemon(253845)] [INFO] espanso version: 2.0.5-alpha
08:42:17 [daemon(253845)] [INFO] spawning the worker process...
08:42:17 [daemon(253845)] [INFO] binded to IPC unix socket: /home/neil/.local/share/espanso/espansodaemonv2.sock
08:42:17 [worker(253852)] [INFO] reading configs from: "/home/neil/.config/espanso"
08:42:17 [worker(253852)] [INFO] reading packages from: "/home/neil/.config/espanso/match/packages"
08:42:17 [worker(253852)] [INFO] using runtime dir: "/home/neil/.local/share/espanso"
08:42:17 [worker(253852)] [INFO] binded to IPC unix socket: /home/neil/.local/share/espanso/espansoworkerv2.sock
08:42:17 [worker(253852)] [INFO] using WaylandAppInfoProvider
08:42:17 [worker(253852)] [WARN] EVDEV backend is being used, but without enabling linux capabilities.
08:42:17 [worker(253852)] [INFO] monitoring the status of the daemon process
08:42:17 [worker(253852)] [WARN]   Although you CAN run espanso EVDEV backend as root, it's not recommended due
08:42:17 [worker(253852)] [WARN]   to security reasons. Espanso supports linux capabilities to limit the attack surface
08:42:17 [worker(253852)] [WARN]   area by only leveraging on the CAP_DAC_OVERRIDE capability (needed to work with
08:42:17 [worker(253852)] [WARN]   /dev/input/* devices to detect and inject text) and disabling it as soon as the
08:42:17 [worker(253852)] [WARN]   initial setup is completed.
08:42:18 [worker(253852)] [INFO] detection module will use this keyboard layout: [R=, M=, L=gb, V=, O=]
08:42:18 [worker(253852)] [INFO] using EVDEVSource
08:42:18 [worker(253852)] [ERROR] Unable to open EVDEV devices, this usually has to do with permissions.
08:42:18 [worker(253852)] [ERROR] You can either add the current user to the 'input' group or run espanso as root
08:42:18 [worker(253852)] [ERROR] thread 'engine thread' panicked at 'failed to initialize detector module: detection source initialization failed': espanso/src/cli/worker/engine/mod.rs:133
08:42:18 [worker(253852)] [ERROR] Unable to block the LinuxEventLoop: receiving on an empty and disconnected channel
08:42:18 [worker(253852)] [ERROR] thread 'main' panicked at 'unable to run main eventloop: receiving on an empty and disconnected channel': espanso/src/cli/worker/mod.rs:160
08:42:18 [daemon(253845)] [ERROR] received unexpected exit code from worker 101, exiting


```

So it looks like

```
sudo setcap "cap_dac_override+p" /home/neil/Downloads/espanso_wayland/espanso/target/release/espanso
```

Is not having the desired effect?

**Comment by federico-terzi** [comment]
@neilzone That's strange, it seems that the `setcap` command is indeed failing for some reason. What do you see when you run the following?

```
getcap /usr/local/bin/espanso
```

**Comment by neilzone** [comment]
> What do you see when you run the following?
> 
> ```
> getcap /usr/local/bin/espanso
> ```

Nothing (a blank exit).
> 
> Perhaps, you might need to apply the capabilities directly to the final destination, like so:
> 
> ```
> sudo setcap "cap_dac_override+p" /usr/local/bin/espanso
> ```

Oddly, I thought had tried that. Perhaps not. On doing that, `espanso` immediately starts with no error / warning in the log, and, if I run `getcap /usr/local/bin/espanso`, I get:

> /usr/local/bin/espanso cap_dac_override=p

Thanks!


I'll give the new alpha a try, and see what happens.

**Comment by federico-terzi** [comment]
Nice! Thanks
