### ISSUE TITLE
Support Emoji in script output

### ISSUE THREAD

**Issue by ytechie** [espanso/espanso#986]
**Describe the bug**
I have a Python script that has some Emoji output. It outputs fine to the console:
![image](https://user-images.githubusercontent.com/1900989/154076752-c70526bd-8658-4df9-b0f8-58ea817f59ea.png)

However, the script fails in Espanso:

> Caused by:
    script reported error: '`Traceback (most recent call last):
      File "C:\Users\jason\AppData\Roaming\espanso\scripts\getcal.py", line 39, in <module>
        print("{}-{} {}".format(start.astimezone().strftime("%I:%M"), end.astimezone().strftime("%I:%M"), event["summary"]))
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode characters in position 12-15: character maps to <undefined>
    `'

A clear and concise description of what the bug is

**To Reproduce**
1. Create a python script that has emoji output

**Expected behavior**
Espanso should be able to output that Emoji

**Screenshots**
See above

**Logs**
See above

**Setup information**
Windows 11 + 2.1.1-alpha
Same issue in MacOS 12.2.1  + 2.1.3-alpha

**Comment by federico-terzi** [comment]
Hey @ytechie,

Thanks for reporting this issue! I suspect there might be a console encoding problem, I'll try investigating further in the next few days :)

If you have the chance, could you please check if this workaround is working for you? https://stackoverflow.com/a/27093194/10850333

Cheers :)

**Comment by ytechie** [comment]
No luck. 

BTW, here is an entire Python script you can test with:

`print("😀")`

**Comment by federico-terzi** [comment]
@ytechie Thanks! We'll investigate :)

**Comment by smeech** [comment]
Is the new documentation about [UTF-8 characters](https://espanso.org/docs/matches/extensions/#utf-8-characters) helpful?

**Comment by smeech** [comment]
Closing due to lack of response. Happy to reopen.
